// ============================================================================
// PROVEN MAPPING — which named strategy actually works on which ticker/timeframe.
//
// Every row below was produced by running the 8 Playbook strategies through the
// SAME realistic-cost backtest engine the rest of the app uses (lib/backtest.ts),
// across the full asset universe (lib/coins.ts) at three horizons:
//   intraday  -> 15m bars (Binance for crypto, Alpaca for stocks)
//   swing     -> 4h crypto / daily stock bars, multi-day holds
//   position  -> daily bars, multi-week holds
//
// These numbers are NOT hand-authored. They were regenerated by the
// /api/playbook-matrix endpoint (which fetches real OHLC and runs the exact
// same backtest), then filtered to keep only pairings that cleared a strict
// robustness bar:
//     trades >= 30  AND  expectancy > 0  AND  profitFactor >= 1.3
//
// 1000 strategy/asset/timeframe combinations were evaluated; 145 passed. Every
// combination that lost money or lacked a sample was dropped, not softened —
// e.g. Momentum Burst on SPY swing (profit factor 0.87) is a real loser and is
// intentionally absent. Intraday is the sparsest horizon: after real 15m costs
// only a handful of names cleared the bar, and we surface exactly those, small
// edges and all, rather than inventing coverage.
//
// "tier" reflects confidence in the edge:
//   strong = large sample (>=60 trades) AND profit factor >= 1.6
//   proven = met the robustness bar above
//
// This is the hidden layer: a user only ever sees a strategy NAME and its proven
// outcome on their ticker. We never surface a pairing that failed testing.
// Regenerate any time data refreshes: `node scripts/regen-matrix.mjs`.
// ============================================================================

export type ProvenTier = "strong" | "proven"

export type PlaybookTimeframe = "intraday" | "swing" | "position"

export type ProvenPairing = {
  strategyId: string
  symbol: string
  timeframe: PlaybookTimeframe
  winRate: number
  expectancy: number
  profitFactor: number
  maxDrawdownR: number
  trades: number
  tier: ProvenTier
}

export const PROVEN_PAIRINGS: ProvenPairing[] = [
  // --- Intraday / same-session (15m bars, flat by the close) ---
  { strategyId: "supertrend-follow", symbol: "AMZN", timeframe: "intraday", winRate: 48.2, expectancy: 0.231, profitFactor: 1.69, maxDrawdownR: 6.65, trades: 83, tier: "strong" },
  { strategyId: "band-fade", symbol: "fantom", timeframe: "intraday", winRate: 76.6, expectancy: 0.853, profitFactor: 4.98, maxDrawdownR: 1.72, trades: 47, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "META", timeframe: "intraday", winRate: 50.7, expectancy: 0.116, profitFactor: 1.37, maxDrawdownR: 7.13, trades: 73, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "MSFT", timeframe: "intraday", winRate: 53, expectancy: 0.212, profitFactor: 1.47, maxDrawdownR: 13.39, trades: 115, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "MSFT", timeframe: "intraday", winRate: 51.4, expectancy: 0.179, profitFactor: 1.5, maxDrawdownR: 4.79, trades: 35, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MSFT", timeframe: "intraday", winRate: 52.8, expectancy: 0.15, profitFactor: 1.4, maxDrawdownR: 7.74, trades: 178, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "TSLA", timeframe: "intraday", winRate: 54.1, expectancy: 0.165, profitFactor: 1.48, maxDrawdownR: 4.55, trades: 85, tier: "proven" },
  // --- Swing (multi-day holds) ---
  { strategyId: "momentum-burst", symbol: "AAPL", timeframe: "swing", winRate: 44.2, expectancy: 0.159, profitFactor: 1.31, maxDrawdownR: 5.31, trades: 104, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AAPL", timeframe: "swing", winRate: 61.4, expectancy: 0.145, profitFactor: 1.51, maxDrawdownR: 4.8, trades: 44, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AMZN", timeframe: "swing", winRate: 57.9, expectancy: 0.181, profitFactor: 1.7, maxDrawdownR: 2.47, trades: 38, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "AMZN", timeframe: "swing", winRate: 54.8, expectancy: 0.128, profitFactor: 1.39, maxDrawdownR: 3.71, trades: 31, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "arbitrum", timeframe: "swing", winRate: 46.9, expectancy: 0.191, profitFactor: 1.44, maxDrawdownR: 6.51, trades: 143, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "cardano", timeframe: "swing", winRate: 52.5, expectancy: 0.22, profitFactor: 1.53, maxDrawdownR: 13.49, trades: 160, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "cardano", timeframe: "swing", winRate: 48, expectancy: 0.157, profitFactor: 1.33, maxDrawdownR: 13.53, trades: 277, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "cardano", timeframe: "swing", winRate: 51.7, expectancy: 0.118, profitFactor: 1.41, maxDrawdownR: 8.83, trades: 89, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "cosmos", timeframe: "swing", winRate: 53.5, expectancy: 0.14, profitFactor: 1.56, maxDrawdownR: 4.51, trades: 86, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "DIA", timeframe: "swing", winRate: 57.5, expectancy: 0.128, profitFactor: 1.46, maxDrawdownR: 5.6, trades: 40, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "dogecoin", timeframe: "swing", winRate: 50, expectancy: 0.169, profitFactor: 1.64, maxDrawdownR: 3.78, trades: 86, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "dogecoin", timeframe: "swing", winRate: 45.1, expectancy: 0.104, profitFactor: 1.3, maxDrawdownR: 7.16, trades: 51, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ethereum", timeframe: "swing", winRate: 47.2, expectancy: 0.088, profitFactor: 1.31, maxDrawdownR: 7.7, trades: 89, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "fantom", timeframe: "swing", winRate: 50, expectancy: 0.242, profitFactor: 1.51, maxDrawdownR: 6.99, trades: 72, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "fantom", timeframe: "swing", winRate: 51.4, expectancy: 0.14, profitFactor: 1.34, maxDrawdownR: 6.65, trades: 37, tier: "proven" },
  { strategyId: "trend-rider", symbol: "fantom", timeframe: "swing", winRate: 51, expectancy: 0.086, profitFactor: 1.34, maxDrawdownR: 2.57, trades: 49, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "GOOGL", timeframe: "swing", winRate: 71.4, expectancy: 0.335, profitFactor: 2.3, maxDrawdownR: 2.05, trades: 35, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GOOGL", timeframe: "swing", winRate: 50.6, expectancy: 0.191, profitFactor: 1.47, maxDrawdownR: 7.28, trades: 83, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "GOOGL", timeframe: "swing", winRate: 54.8, expectancy: 0.181, profitFactor: 1.43, maxDrawdownR: 3.57, trades: 42, tier: "proven" },
  { strategyId: "trend-rider", symbol: "GOOGL", timeframe: "swing", winRate: 58.1, expectancy: 0.18, profitFactor: 1.6, maxDrawdownR: 5.07, trades: 74, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "internet-computer", timeframe: "swing", winRate: 47.2, expectancy: 0.145, profitFactor: 1.32, maxDrawdownR: 8.65, trades: 142, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "internet-computer", timeframe: "swing", winRate: 48.3, expectancy: 0.097, profitFactor: 1.31, maxDrawdownR: 4.05, trades: 87, tier: "proven" },
  { strategyId: "band-fade", symbol: "litecoin", timeframe: "swing", winRate: 56.6, expectancy: 0.248, profitFactor: 1.54, maxDrawdownR: 6.56, trades: 53, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "matic-network", timeframe: "swing", winRate: 47.5, expectancy: 0.177, profitFactor: 1.38, maxDrawdownR: 20.33, trades: 242, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "matic-network", timeframe: "swing", winRate: 49.3, expectancy: 0.112, profitFactor: 1.33, maxDrawdownR: 6.21, trades: 73, tier: "proven" },
  { strategyId: "trend-rider", symbol: "matic-network", timeframe: "swing", winRate: 52.2, expectancy: 0.109, profitFactor: 1.44, maxDrawdownR: 5.09, trades: 201, tier: "proven" },
  { strategyId: "golden-trend", symbol: "META", timeframe: "swing", winRate: 58, expectancy: 0.218, profitFactor: 1.59, maxDrawdownR: 4.25, trades: 88, tier: "proven" },
  { strategyId: "trend-rider", symbol: "META", timeframe: "swing", winRate: 56.9, expectancy: 0.202, profitFactor: 1.7, maxDrawdownR: 4.37, trades: 72, tier: "strong" },
  { strategyId: "golden-trend", symbol: "MSFT", timeframe: "swing", winRate: 53.8, expectancy: 0.164, profitFactor: 1.42, maxDrawdownR: 5.51, trades: 78, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MSFT", timeframe: "swing", winRate: 63.1, expectancy: 0.136, profitFactor: 1.49, maxDrawdownR: 4.86, trades: 65, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "NVDA", timeframe: "swing", winRate: 51.1, expectancy: 0.323, profitFactor: 1.73, maxDrawdownR: 5.29, trades: 45, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NVDA", timeframe: "swing", winRate: 47.3, expectancy: 0.304, profitFactor: 1.65, maxDrawdownR: 6.28, trades: 93, tier: "strong" },
  { strategyId: "trend-rider", symbol: "NVDA", timeframe: "swing", winRate: 54.9, expectancy: 0.267, profitFactor: 1.88, maxDrawdownR: 3.74, trades: 71, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "polkadot", timeframe: "swing", winRate: 53.4, expectancy: 0.246, profitFactor: 1.62, maxDrawdownR: 4.64, trades: 148, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "polkadot", timeframe: "swing", winRate: 54.3, expectancy: 0.149, profitFactor: 1.58, maxDrawdownR: 3.4, trades: 81, tier: "proven" },
  { strategyId: "golden-trend", symbol: "QQQ", timeframe: "swing", winRate: 49.4, expectancy: 0.248, profitFactor: 1.58, maxDrawdownR: 6.73, trades: 89, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "QQQ", timeframe: "swing", winRate: 62.5, expectancy: 0.212, profitFactor: 1.77, maxDrawdownR: 3.09, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "QQQ", timeframe: "swing", winRate: 59, expectancy: 0.111, profitFactor: 1.35, maxDrawdownR: 3.57, trades: 78, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "render-token", timeframe: "swing", winRate: 48.9, expectancy: 0.163, profitFactor: 1.4, maxDrawdownR: 7.68, trades: 133, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "ripple", timeframe: "swing", winRate: 41.1, expectancy: 0.114, profitFactor: 1.44, maxDrawdownR: 3.97, trades: 56, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sei-network", timeframe: "swing", winRate: 49.3, expectancy: 0.179, profitFactor: 1.43, maxDrawdownR: 8.32, trades: 152, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SPX", timeframe: "swing", winRate: 52.8, expectancy: 0.172, profitFactor: 1.37, maxDrawdownR: 6.07, trades: 127, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SPX", timeframe: "swing", winRate: 64.8, expectancy: 0.138, profitFactor: 1.44, maxDrawdownR: 6.27, trades: 54, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "SPX", timeframe: "swing", winRate: 56.7, expectancy: 0.127, profitFactor: 1.37, maxDrawdownR: 5.82, trades: 67, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SPY", timeframe: "swing", winRate: 58.1, expectancy: 0.238, profitFactor: 1.59, maxDrawdownR: 4.89, trades: 86, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SPY", timeframe: "swing", winRate: 58.4, expectancy: 0.119, profitFactor: 1.35, maxDrawdownR: 5.48, trades: 77, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "stellar", timeframe: "swing", winRate: 49.4, expectancy: 0.205, profitFactor: 1.49, maxDrawdownR: 5.73, trades: 154, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "stellar", timeframe: "swing", winRate: 51.1, expectancy: 0.114, profitFactor: 1.42, maxDrawdownR: 3.11, trades: 90, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sui", timeframe: "swing", winRate: 48.7, expectancy: 0.174, profitFactor: 1.45, maxDrawdownR: 6.55, trades: 150, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "tron", timeframe: "swing", winRate: 51.5, expectancy: 0.13, profitFactor: 1.4, maxDrawdownR: 8.45, trades: 101, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "TSLA", timeframe: "swing", winRate: 44, expectancy: 0.201, profitFactor: 1.48, maxDrawdownR: 3.3, trades: 50, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "uniswap", timeframe: "swing", winRate: 48.9, expectancy: 0.103, profitFactor: 1.32, maxDrawdownR: 7.53, trades: 88, tier: "proven" },
  // --- Position (multi-week holds) ---
  { strategyId: "momentum-burst", symbol: "AAPL", timeframe: "position", winRate: 46.3, expectancy: 0.212, profitFactor: 1.39, maxDrawdownR: 5.31, trades: 95, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AAPL", timeframe: "position", winRate: 51.3, expectancy: 0.133, profitFactor: 1.33, maxDrawdownR: 4.92, trades: 39, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AMZN", timeframe: "position", winRate: 58.8, expectancy: 0.246, profitFactor: 1.83, maxDrawdownR: 2.32, trades: 34, tier: "proven" },
  { strategyId: "trend-rider", symbol: "aptos", timeframe: "position", winRate: 58.8, expectancy: 0.179, profitFactor: 1.81, maxDrawdownR: 1.88, trades: 51, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "arbitrum", timeframe: "position", winRate: 47.2, expectancy: 0.254, profitFactor: 1.56, maxDrawdownR: 4.18, trades: 36, tier: "proven" },
  { strategyId: "golden-trend", symbol: "arbitrum", timeframe: "position", winRate: 52.3, expectancy: 0.231, profitFactor: 1.63, maxDrawdownR: 5.32, trades: 44, tier: "proven" },
  { strategyId: "trend-rider", symbol: "arbitrum", timeframe: "position", winRate: 55.8, expectancy: 0.119, profitFactor: 1.37, maxDrawdownR: 6.4, trades: 43, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "avalanche-2", timeframe: "position", winRate: 55.1, expectancy: 0.403, profitFactor: 2.03, maxDrawdownR: 4.37, trades: 69, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "avalanche-2", timeframe: "position", winRate: 56.1, expectancy: 0.306, profitFactor: 1.93, maxDrawdownR: 3.04, trades: 41, tier: "proven" },
  { strategyId: "trend-rider", symbol: "avalanche-2", timeframe: "position", winRate: 54.5, expectancy: 0.252, profitFactor: 1.86, maxDrawdownR: 2.73, trades: 77, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "avalanche-2", timeframe: "position", winRate: 44.1, expectancy: 0.161, profitFactor: 1.31, maxDrawdownR: 7.22, trades: 111, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "binancecoin", timeframe: "position", winRate: 51.6, expectancy: 0.414, profitFactor: 1.91, maxDrawdownR: 3.42, trades: 64, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "binancecoin", timeframe: "position", winRate: 59.4, expectancy: 0.28, profitFactor: 2.19, maxDrawdownR: 3.21, trades: 32, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "binancecoin", timeframe: "position", winRate: 47.2, expectancy: 0.27, profitFactor: 1.55, maxDrawdownR: 6.04, trades: 125, tier: "proven" },
  { strategyId: "trend-rider", symbol: "binancecoin", timeframe: "position", winRate: 45.5, expectancy: 0.191, profitFactor: 1.58, maxDrawdownR: 6.12, trades: 88, tier: "proven" },
  { strategyId: "golden-trend", symbol: "bitcoin", timeframe: "position", winRate: 47.8, expectancy: 0.257, profitFactor: 1.62, maxDrawdownR: 4.93, trades: 90, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "bitcoin", timeframe: "position", winRate: 48.6, expectancy: 0.238, profitFactor: 1.49, maxDrawdownR: 5.52, trades: 72, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "bitcoin", timeframe: "position", winRate: 43.6, expectancy: 0.16, profitFactor: 1.3, maxDrawdownR: 7.6, trades: 110, tier: "proven" },
  { strategyId: "trend-rider", symbol: "bitcoin", timeframe: "position", winRate: 46.9, expectancy: 0.149, profitFactor: 1.47, maxDrawdownR: 6.43, trades: 81, tier: "proven" },
  { strategyId: "trend-rider", symbol: "cardano", timeframe: "position", winRate: 56.3, expectancy: 0.161, profitFactor: 1.5, maxDrawdownR: 3.58, trades: 87, tier: "proven" },
  { strategyId: "band-fade", symbol: "cardano", timeframe: "position", winRate: 50, expectancy: 0.158, profitFactor: 1.31, maxDrawdownR: 3.09, trades: 42, tier: "proven" },
  { strategyId: "golden-trend", symbol: "cardano", timeframe: "position", winRate: 46.7, expectancy: 0.149, profitFactor: 1.33, maxDrawdownR: 8.83, trades: 107, tier: "proven" },
  { strategyId: "golden-trend", symbol: "DIA", timeframe: "position", winRate: 46.6, expectancy: 0.21, profitFactor: 1.41, maxDrawdownR: 6.8, trades: 73, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "dogecoin", timeframe: "position", winRate: 57.5, expectancy: 0.333, profitFactor: 2.43, maxDrawdownR: 2.02, trades: 40, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "dogecoin", timeframe: "position", winRate: 48.5, expectancy: 0.267, profitFactor: 1.57, maxDrawdownR: 5.74, trades: 66, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "dogecoin", timeframe: "position", winRate: 45.2, expectancy: 0.197, profitFactor: 1.38, maxDrawdownR: 7.47, trades: 124, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "ethereum", timeframe: "position", winRate: 44.6, expectancy: 0.158, profitFactor: 1.32, maxDrawdownR: 7.47, trades: 65, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "ethereum", timeframe: "position", winRate: 43.8, expectancy: 0.136, profitFactor: 1.34, maxDrawdownR: 3.39, trades: 32, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "fantom", timeframe: "position", winRate: 53.6, expectancy: 0.446, profitFactor: 2.13, maxDrawdownR: 3.82, trades: 56, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "fantom", timeframe: "position", winRate: 61.3, expectancy: 0.353, profitFactor: 2.61, maxDrawdownR: 1.77, trades: 31, tier: "proven" },
  { strategyId: "golden-trend", symbol: "fantom", timeframe: "position", winRate: 50, expectancy: 0.333, profitFactor: 1.74, maxDrawdownR: 6.14, trades: 72, tier: "strong" },
  { strategyId: "trend-rider", symbol: "fantom", timeframe: "position", winRate: 57.1, expectancy: 0.328, profitFactor: 2.15, maxDrawdownR: 2.7, trades: 63, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "fantom", timeframe: "position", winRate: 44.9, expectancy: 0.199, profitFactor: 1.4, maxDrawdownR: 7.41, trades: 89, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "filecoin", timeframe: "position", winRate: 64.5, expectancy: 0.501, profitFactor: 3.05, maxDrawdownR: 2.89, trades: 31, tier: "proven" },
  { strategyId: "band-fade", symbol: "filecoin", timeframe: "position", winRate: 48.8, expectancy: 0.262, profitFactor: 1.59, maxDrawdownR: 3.6, trades: 41, tier: "proven" },
  { strategyId: "trend-rider", symbol: "filecoin", timeframe: "position", winRate: 57.8, expectancy: 0.124, profitFactor: 1.44, maxDrawdownR: 4.86, trades: 83, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GOOGL", timeframe: "position", winRate: 44.6, expectancy: 0.251, profitFactor: 1.53, maxDrawdownR: 6.54, trades: 65, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "GOOGL", timeframe: "position", winRate: 48.8, expectancy: 0.25, profitFactor: 1.52, maxDrawdownR: 5.29, trades: 41, tier: "proven" },
  { strategyId: "trend-rider", symbol: "GOOGL", timeframe: "position", winRate: 55.4, expectancy: 0.242, profitFactor: 1.66, maxDrawdownR: 3.79, trades: 56, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "hedera-hashgraph", timeframe: "position", winRate: 60, expectancy: 0.22, profitFactor: 1.74, maxDrawdownR: 2.83, trades: 35, tier: "proven" },
  { strategyId: "golden-trend", symbol: "hedera-hashgraph", timeframe: "position", winRate: 44.9, expectancy: 0.143, profitFactor: 1.34, maxDrawdownR: 7.78, trades: 98, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "injective-protocol", timeframe: "position", winRate: 44.4, expectancy: 0.218, profitFactor: 1.49, maxDrawdownR: 9.59, trades: 63, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "injective-protocol", timeframe: "position", winRate: 54.8, expectancy: 0.187, profitFactor: 1.69, maxDrawdownR: 3.44, trades: 31, tier: "proven" },
  { strategyId: "trend-rider", symbol: "injective-protocol", timeframe: "position", winRate: 53.7, expectancy: 0.096, profitFactor: 1.31, maxDrawdownR: 6.85, trades: 82, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "internet-computer", timeframe: "position", winRate: 50.9, expectancy: 0.271, profitFactor: 1.67, maxDrawdownR: 5.44, trades: 53, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "internet-computer", timeframe: "position", winRate: 47.5, expectancy: 0.152, profitFactor: 1.32, maxDrawdownR: 6.06, trades: 101, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "matic-network", timeframe: "position", winRate: 63.6, expectancy: 0.411, profitFactor: 2.23, maxDrawdownR: 3.04, trades: 33, tier: "proven" },
  { strategyId: "golden-trend", symbol: "META", timeframe: "position", winRate: 52.1, expectancy: 0.339, profitFactor: 1.79, maxDrawdownR: 4.33, trades: 71, tier: "strong" },
  { strategyId: "trend-rider", symbol: "META", timeframe: "position", winRate: 55.2, expectancy: 0.198, profitFactor: 1.59, maxDrawdownR: 5.06, trades: 58, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "near", timeframe: "position", winRate: 55.1, expectancy: 0.257, profitFactor: 1.6, maxDrawdownR: 8.59, trades: 69, tier: "strong" },
  { strategyId: "golden-trend", symbol: "near", timeframe: "position", winRate: 48.4, expectancy: 0.166, profitFactor: 1.37, maxDrawdownR: 7.77, trades: 93, tier: "proven" },
  { strategyId: "trend-rider", symbol: "near", timeframe: "position", winRate: 50, expectancy: 0.148, profitFactor: 1.41, maxDrawdownR: 6.98, trades: 80, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NVDA", timeframe: "position", winRate: 47.5, expectancy: 0.331, profitFactor: 1.67, maxDrawdownR: 6.08, trades: 80, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "NVDA", timeframe: "position", winRate: 52.3, expectancy: 0.293, profitFactor: 1.62, maxDrawdownR: 6.09, trades: 44, tier: "proven" },
  { strategyId: "trend-rider", symbol: "NVDA", timeframe: "position", winRate: 56.1, expectancy: 0.291, profitFactor: 1.84, maxDrawdownR: 3.77, trades: 57, tier: "proven" },
  { strategyId: "trend-rider", symbol: "optimism", timeframe: "position", winRate: 50.9, expectancy: 0.138, profitFactor: 1.44, maxDrawdownR: 4.38, trades: 55, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "polkadot", timeframe: "position", winRate: 53.1, expectancy: 0.361, profitFactor: 2.43, maxDrawdownR: 2.27, trades: 32, tier: "proven" },
  { strategyId: "band-fade", symbol: "polkadot", timeframe: "position", winRate: 51.6, expectancy: 0.218, profitFactor: 1.44, maxDrawdownR: 4.17, trades: 31, tier: "proven" },
  { strategyId: "golden-trend", symbol: "polkadot", timeframe: "position", winRate: 49.5, expectancy: 0.174, profitFactor: 1.41, maxDrawdownR: 5.68, trades: 97, tier: "proven" },
  { strategyId: "golden-trend", symbol: "QQQ", timeframe: "position", winRate: 50.7, expectancy: 0.305, profitFactor: 1.63, maxDrawdownR: 5.93, trades: 69, tier: "strong" },
  { strategyId: "trend-rider", symbol: "QQQ", timeframe: "position", winRate: 54.2, expectancy: 0.19, profitFactor: 1.51, maxDrawdownR: 4.03, trades: 59, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "QQQ", timeframe: "position", winRate: 43.2, expectancy: 0.172, profitFactor: 1.32, maxDrawdownR: 4.13, trades: 37, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sei-network", timeframe: "position", winRate: 53.1, expectancy: 0.315, profitFactor: 1.76, maxDrawdownR: 2.77, trades: 32, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "sei-network", timeframe: "position", winRate: 50, expectancy: 0.253, profitFactor: 1.51, maxDrawdownR: 6.1, trades: 52, tier: "proven" },
  { strategyId: "golden-trend", symbol: "solana", timeframe: "position", winRate: 51, expectancy: 0.343, profitFactor: 1.8, maxDrawdownR: 6.42, trades: 102, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "solana", timeframe: "position", winRate: 50, expectancy: 0.219, profitFactor: 1.46, maxDrawdownR: 8.43, trades: 74, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "solana", timeframe: "position", winRate: 62.9, expectancy: 0.219, profitFactor: 1.83, maxDrawdownR: 4.48, trades: 35, tier: "proven" },
  { strategyId: "trend-rider", symbol: "solana", timeframe: "position", winRate: 48.2, expectancy: 0.217, profitFactor: 1.6, maxDrawdownR: 5.06, trades: 83, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "SPX", timeframe: "position", winRate: 46.3, expectancy: 0.185, profitFactor: 1.34, maxDrawdownR: 4.74, trades: 54, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SPX", timeframe: "position", winRate: 60, expectancy: 0.119, profitFactor: 1.32, maxDrawdownR: 8.14, trades: 100, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SPY", timeframe: "position", winRate: 48.5, expectancy: 0.29, profitFactor: 1.62, maxDrawdownR: 5.83, trades: 66, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "SPY", timeframe: "position", winRate: 47.1, expectancy: 0.208, profitFactor: 1.44, maxDrawdownR: 4.83, trades: 34, tier: "proven" },
  { strategyId: "band-fade", symbol: "stellar", timeframe: "position", winRate: 62.5, expectancy: 0.564, profitFactor: 2.55, maxDrawdownR: 3.19, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "sui", timeframe: "position", winRate: 53.7, expectancy: 0.219, profitFactor: 1.82, maxDrawdownR: 4.45, trades: 41, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "sui", timeframe: "position", winRate: 45.9, expectancy: 0.199, profitFactor: 1.37, maxDrawdownR: 5.91, trades: 61, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sui", timeframe: "position", winRate: 47.2, expectancy: 0.18, profitFactor: 1.35, maxDrawdownR: 3.17, trades: 36, tier: "proven" },
  { strategyId: "golden-trend", symbol: "sui", timeframe: "position", winRate: 46.8, expectancy: 0.172, profitFactor: 1.34, maxDrawdownR: 4.16, trades: 47, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "the-graph", timeframe: "position", winRate: 53.5, expectancy: 0.27, profitFactor: 1.63, maxDrawdownR: 5.14, trades: 101, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "the-graph", timeframe: "position", winRate: 50, expectancy: 0.192, profitFactor: 1.46, maxDrawdownR: 3.53, trades: 64, tier: "proven" },
  { strategyId: "trend-rider", symbol: "the-graph", timeframe: "position", winRate: 57.1, expectancy: 0.105, profitFactor: 1.37, maxDrawdownR: 5.12, trades: 77, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "tron", timeframe: "position", winRate: 62.2, expectancy: 0.353, profitFactor: 2.18, maxDrawdownR: 3.51, trades: 45, tier: "proven" },
  { strategyId: "trend-rider", symbol: "tron", timeframe: "position", winRate: 58.1, expectancy: 0.325, profitFactor: 2.25, maxDrawdownR: 5.02, trades: 86, tier: "strong" },
  { strategyId: "band-fade", symbol: "tron", timeframe: "position", winRate: 50, expectancy: 0.207, profitFactor: 1.39, maxDrawdownR: 5.13, trades: 36, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "tron", timeframe: "position", winRate: 45.2, expectancy: 0.193, profitFactor: 1.37, maxDrawdownR: 4.13, trades: 62, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "TSLA", timeframe: "position", winRate: 47.1, expectancy: 0.288, profitFactor: 1.78, maxDrawdownR: 2.99, trades: 34, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "TSLA", timeframe: "position", winRate: 48.9, expectancy: 0.229, profitFactor: 1.46, maxDrawdownR: 5.61, trades: 47, tier: "proven" },
]

// All pairings for a given ticker, best edge first.
export function provenForSymbol(symbol: string): ProvenPairing[] {
  return PROVEN_PAIRINGS.filter((p) => p.symbol === symbol).sort((a, b) => b.expectancy - a.expectancy)
}

// The single best-fit strategy for a ticker (optionally at a fixed timeframe).
export function bestForSymbol(symbol: string, timeframe?: PlaybookTimeframe): ProvenPairing | null {
  const list = provenForSymbol(symbol).filter((p) => !timeframe || p.timeframe === timeframe)
  return list[0] ?? null
}

// Exact stats for one strategy/ticker/timeframe assignment, or null if it never
// passed testing (so the UI can honestly say "not proven on this market").
export function statsFor(
  strategyId: string,
  symbol: string,
  timeframe: PlaybookTimeframe,
): ProvenPairing | null {
  return (
    PROVEN_PAIRINGS.find(
      (p) => p.strategyId === strategyId && p.symbol === symbol && p.timeframe === timeframe,
    ) ?? null
  )
}

// Every ticker that has at least one proven strategy.
export function provenSymbols(): string[] {
  return Array.from(new Set(PROVEN_PAIRINGS.map((p) => p.symbol)))
}
