// ============================================================================
// PROVEN MAPPING — which named strategy actually works on which ticker/timeframe.
//
// Every row below was produced by running the 8 Playbook strategies through the
// SAME realistic-cost backtest engine the rest of the app uses, across the full
// asset universe at swing and position timeframes. Only pairings that cleared a
// strict robustness bar are kept:
//     trades >= 30  AND  expectancy > 0  AND  profitFactor >= 1.3
//
// "tier" reflects confidence in the edge:
//   strong = large sample (>=60 trades) AND profit factor >= 1.6
//   proven = met the robustness bar above
//
// This is the hidden layer: a user only ever sees a strategy NAME and its proven
// outcome on their ticker. We never surface a pairing that failed testing.
// Regenerate with the /api/playbook-matrix endpoint if data is refreshed.
// ============================================================================

export type ProvenTier = "strong" | "proven"

export type ProvenPairing = {
  strategyId: string
  symbol: string
  timeframe: "swing" | "position"
  winRate: number
  expectancy: number
  profitFactor: number
  maxDrawdownR: number
  trades: number
  tier: ProvenTier
}

export const PROVEN_PAIRINGS: ProvenPairing[] = [
  // --- US stocks & ETFs (validated on Alpaca data) ---
  { strategyId: "momentum-burst", symbol: "AAPL", timeframe: "position", winRate: 45.7, expectancy: 0.209, profitFactor: 1.38, maxDrawdownR: 5.31, trades: 94, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AAPL", timeframe: "position", winRate: 53.8, expectancy: 0.169, profitFactor: 1.45, maxDrawdownR: 4.92, trades: 39, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "AAPL", timeframe: "swing", winRate: 43.7, expectancy: 0.156, profitFactor: 1.3, maxDrawdownR: 5.31, trades: 103, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AAPL", timeframe: "swing", winRate: 60.5, expectancy: 0.151, profitFactor: 1.52, maxDrawdownR: 4.8, trades: 43, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AMZN", timeframe: "position", winRate: 58.8, expectancy: 0.248, profitFactor: 1.84, maxDrawdownR: 2.32, trades: 34, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AMZN", timeframe: "swing", winRate: 57.9, expectancy: 0.181, profitFactor: 1.7, maxDrawdownR: 2.47, trades: 38, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "AMZN", timeframe: "swing", winRate: 54.8, expectancy: 0.128, profitFactor: 1.39, maxDrawdownR: 3.71, trades: 31, tier: "proven" },
  { strategyId: "golden-trend", symbol: "DIA", timeframe: "position", winRate: 46.6, expectancy: 0.203, profitFactor: 1.39, maxDrawdownR: 6.8, trades: 73, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "DIA", timeframe: "swing", winRate: 57.5, expectancy: 0.121, profitFactor: 1.43, maxDrawdownR: 5.6, trades: 40, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "GOOGL", timeframe: "swing", winRate: 70.6, expectancy: 0.339, profitFactor: 2.28, maxDrawdownR: 2.05, trades: 34, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "GOOGL", timeframe: "position", winRate: 48.8, expectancy: 0.26, profitFactor: 1.54, maxDrawdownR: 5.29, trades: 41, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GOOGL", timeframe: "position", winRate: 43.8, expectancy: 0.25, profitFactor: 1.52, maxDrawdownR: 6.54, trades: 64, tier: "proven" },
  { strategyId: "trend-rider", symbol: "GOOGL", timeframe: "position", winRate: 54.5, expectancy: 0.243, profitFactor: 1.65, maxDrawdownR: 3.79, trades: 55, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GOOGL", timeframe: "swing", winRate: 50, expectancy: 0.19, profitFactor: 1.46, maxDrawdownR: 7.28, trades: 82, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "GOOGL", timeframe: "swing", winRate: 54.8, expectancy: 0.186, profitFactor: 1.45, maxDrawdownR: 3.57, trades: 42, tier: "proven" },
  { strategyId: "trend-rider", symbol: "GOOGL", timeframe: "swing", winRate: 57.5, expectancy: 0.18, profitFactor: 1.59, maxDrawdownR: 5.07, trades: 73, tier: "proven" },
  { strategyId: "golden-trend", symbol: "META", timeframe: "position", winRate: 53.5, expectancy: 0.353, profitFactor: 1.83, maxDrawdownR: 4.07, trades: 71, tier: "strong" },
  { strategyId: "golden-trend", symbol: "META", timeframe: "swing", winRate: 59.3, expectancy: 0.241, profitFactor: 1.66, maxDrawdownR: 4.13, trades: 86, tier: "strong" },
  { strategyId: "trend-rider", symbol: "META", timeframe: "swing", winRate: 56.9, expectancy: 0.215, profitFactor: 1.78, maxDrawdownR: 4.08, trades: 72, tier: "strong" },
  { strategyId: "trend-rider", symbol: "META", timeframe: "position", winRate: 56.9, expectancy: 0.21, profitFactor: 1.64, maxDrawdownR: 5.06, trades: 58, tier: "proven" },
  { strategyId: "golden-trend", symbol: "MSFT", timeframe: "swing", winRate: 54.5, expectancy: 0.177, profitFactor: 1.46, maxDrawdownR: 5.51, trades: 77, tier: "proven" },
  { strategyId: "golden-trend", symbol: "MSFT", timeframe: "position", winRate: 48.4, expectancy: 0.15, profitFactor: 1.32, maxDrawdownR: 7.02, trades: 62, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MSFT", timeframe: "swing", winRate: 63.1, expectancy: 0.146, profitFactor: 1.53, maxDrawdownR: 4.86, trades: 65, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NVDA", timeframe: "position", winRate: 47.5, expectancy: 0.331, profitFactor: 1.67, maxDrawdownR: 6.08, trades: 80, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "NVDA", timeframe: "swing", winRate: 51.1, expectancy: 0.323, profitFactor: 1.73, maxDrawdownR: 5.29, trades: 45, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NVDA", timeframe: "swing", winRate: 47.3, expectancy: 0.304, profitFactor: 1.65, maxDrawdownR: 6.28, trades: 93, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "NVDA", timeframe: "position", winRate: 52.3, expectancy: 0.295, profitFactor: 1.62, maxDrawdownR: 6.09, trades: 44, tier: "proven" },
  { strategyId: "trend-rider", symbol: "NVDA", timeframe: "position", winRate: 56.1, expectancy: 0.29, profitFactor: 1.83, maxDrawdownR: 3.82, trades: 57, tier: "proven" },
  { strategyId: "trend-rider", symbol: "NVDA", timeframe: "swing", winRate: 54.9, expectancy: 0.266, profitFactor: 1.87, maxDrawdownR: 3.74, trades: 71, tier: "strong" },
  { strategyId: "golden-trend", symbol: "QQQ", timeframe: "position", winRate: 50.7, expectancy: 0.311, profitFactor: 1.64, maxDrawdownR: 5.93, trades: 69, tier: "strong" },
  { strategyId: "golden-trend", symbol: "QQQ", timeframe: "swing", winRate: 50, expectancy: 0.251, profitFactor: 1.59, maxDrawdownR: 6.73, trades: 88, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "QQQ", timeframe: "swing", winRate: 67.7, expectancy: 0.235, profitFactor: 1.86, maxDrawdownR: 3.09, trades: 31, tier: "proven" },
  { strategyId: "trend-rider", symbol: "QQQ", timeframe: "position", winRate: 55.9, expectancy: 0.195, profitFactor: 1.52, maxDrawdownR: 4.03, trades: 59, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "QQQ", timeframe: "position", winRate: 43.2, expectancy: 0.172, profitFactor: 1.32, maxDrawdownR: 4.13, trades: 37, tier: "proven" },
  { strategyId: "trend-rider", symbol: "QQQ", timeframe: "swing", winRate: 61, expectancy: 0.119, profitFactor: 1.38, maxDrawdownR: 3.57, trades: 77, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SPY", timeframe: "position", winRate: 48.5, expectancy: 0.284, profitFactor: 1.61, maxDrawdownR: 5.83, trades: 66, tier: "strong" },
  { strategyId: "golden-trend", symbol: "SPY", timeframe: "swing", winRate: 57.6, expectancy: 0.236, profitFactor: 1.58, maxDrawdownR: 4.89, trades: 85, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "SPY", timeframe: "position", winRate: 47.1, expectancy: 0.208, profitFactor: 1.44, maxDrawdownR: 4.83, trades: 34, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SPY", timeframe: "swing", winRate: 58.4, expectancy: 0.114, profitFactor: 1.34, maxDrawdownR: 5.48, trades: 77, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "TSLA", timeframe: "position", winRate: 47.1, expectancy: 0.287, profitFactor: 1.78, maxDrawdownR: 2.99, trades: 34, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "TSLA", timeframe: "position", winRate: 48.9, expectancy: 0.234, profitFactor: 1.48, maxDrawdownR: 5.38, trades: 47, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "TSLA", timeframe: "swing", winRate: 44, expectancy: 0.205, profitFactor: 1.5, maxDrawdownR: 3.3, trades: 50, tier: "proven" },
  // --- Crypto (validated on Binance data) ---
  { strategyId: "breakout-hunter", symbol: "avalanche-2", timeframe: "position", winRate: 55.1, expectancy: 0.406, profitFactor: 2.05, maxDrawdownR: 4.37, trades: 69, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "avalanche-2", timeframe: "position", winRate: 56.1, expectancy: 0.306, profitFactor: 1.93, maxDrawdownR: 3.04, trades: 41, tier: "proven" },
  { strategyId: "trend-rider", symbol: "avalanche-2", timeframe: "position", winRate: 53.1, expectancy: 0.22, profitFactor: 1.67, maxDrawdownR: 4.02, trades: 81, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "avalanche-2", timeframe: "position", winRate: 44.1, expectancy: 0.161, profitFactor: 1.31, maxDrawdownR: 7.22, trades: 111, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "binancecoin", timeframe: "position", winRate: 50.8, expectancy: 0.392, profitFactor: 1.84, maxDrawdownR: 3.63, trades: 65, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "binancecoin", timeframe: "position", winRate: 60.6, expectancy: 0.339, profitFactor: 2.43, maxDrawdownR: 3.5, trades: 33, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "binancecoin", timeframe: "position", winRate: 47.2, expectancy: 0.257, profitFactor: 1.52, maxDrawdownR: 6.04, trades: 127, tier: "proven" },
  { strategyId: "golden-trend", symbol: "binancecoin", timeframe: "position", winRate: 47.5, expectancy: 0.255, profitFactor: 1.62, maxDrawdownR: 6.9, trades: 101, tier: "strong" },
  { strategyId: "trend-rider", symbol: "binancecoin", timeframe: "position", winRate: 45.1, expectancy: 0.148, profitFactor: 1.43, maxDrawdownR: 6.57, trades: 91, tier: "proven" },
  { strategyId: "golden-trend", symbol: "bitcoin", timeframe: "position", winRate: 49.4, expectancy: 0.271, profitFactor: 1.68, maxDrawdownR: 5.06, trades: 89, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "bitcoin", timeframe: "position", winRate: 47.9, expectancy: 0.22, profitFactor: 1.45, maxDrawdownR: 5.52, trades: 73, tier: "proven" },
  { strategyId: "trend-rider", symbol: "bitcoin", timeframe: "position", winRate: 49.4, expectancy: 0.161, profitFactor: 1.53, maxDrawdownR: 5.71, trades: 83, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "bitcoin", timeframe: "position", winRate: 43.2, expectancy: 0.159, profitFactor: 1.3, maxDrawdownR: 7.6, trades: 111, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "cardano", timeframe: "swing", winRate: 52.2, expectancy: 0.209, profitFactor: 1.5, maxDrawdownR: 13.49, trades: 159, tier: "proven" },
  { strategyId: "golden-trend", symbol: "cardano", timeframe: "position", winRate: 48.1, expectancy: 0.17, profitFactor: 1.37, maxDrawdownR: 9.05, trades: 106, tier: "proven" },
  { strategyId: "trend-rider", symbol: "cardano", timeframe: "position", winRate: 55.7, expectancy: 0.16, profitFactor: 1.49, maxDrawdownR: 5.96, trades: 88, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "cardano", timeframe: "swing", winRate: 47.8, expectancy: 0.149, profitFactor: 1.31, maxDrawdownR: 13.53, trades: 278, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "cardano", timeframe: "swing", winRate: 51.1, expectancy: 0.091, profitFactor: 1.32, maxDrawdownR: 8.83, trades: 88, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "dogecoin", timeframe: "position", winRate: 58.5, expectancy: 0.334, profitFactor: 2.47, maxDrawdownR: 2.02, trades: 41, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "dogecoin", timeframe: "position", winRate: 50, expectancy: 0.28, profitFactor: 1.61, maxDrawdownR: 5.74, trades: 66, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "dogecoin", timeframe: "position", winRate: 45.2, expectancy: 0.201, profitFactor: 1.39, maxDrawdownR: 7.47, trades: 126, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "dogecoin", timeframe: "swing", winRate: 49.4, expectancy: 0.168, profitFactor: 1.63, maxDrawdownR: 3.78, trades: 85, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "dogecoin", timeframe: "swing", winRate: 45.1, expectancy: 0.116, profitFactor: 1.35, maxDrawdownR: 6.12, trades: 51, tier: "proven" },
  { strategyId: "trend-rider", symbol: "dogecoin", timeframe: "position", winRate: 47.7, expectancy: 0.11, profitFactor: 1.33, maxDrawdownR: 10.27, trades: 86, tier: "proven" },
  { strategyId: "trend-rider", symbol: "dogecoin", timeframe: "swing", winRate: 51.3, expectancy: 0.108, profitFactor: 1.38, maxDrawdownR: 5.98, trades: 238, tier: "proven" },
  { strategyId: "golden-trend", symbol: "ethereum", timeframe: "position", winRate: 44.6, expectancy: 0.15, profitFactor: 1.33, maxDrawdownR: 9.77, trades: 92, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "ethereum", timeframe: "position", winRate: 45.5, expectancy: 0.147, profitFactor: 1.38, maxDrawdownR: 4.03, trades: 33, tier: "proven" },
  { strategyId: "golden-trend", symbol: "solana", timeframe: "position", winRate: 52.5, expectancy: 0.33, profitFactor: 1.78, maxDrawdownR: 6.42, trades: 101, tier: "strong" },
  { strategyId: "trend-rider", symbol: "solana", timeframe: "position", winRate: 48.2, expectancy: 0.232, profitFactor: 1.65, maxDrawdownR: 5.87, trades: 83, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "solana", timeframe: "position", winRate: 61.8, expectancy: 0.216, profitFactor: 1.79, maxDrawdownR: 4.48, trades: 34, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "solana", timeframe: "position", winRate: 49.3, expectancy: 0.215, profitFactor: 1.45, maxDrawdownR: 8.43, trades: 73, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "solana", timeframe: "swing", winRate: 46.5, expectancy: 0.141, profitFactor: 1.31, maxDrawdownR: 20.61, trades: 155, tier: "proven" },
  { strategyId: "trend-rider", symbol: "sui", timeframe: "position", winRate: 56.1, expectancy: 0.202, profitFactor: 1.7, maxDrawdownR: 5.4, trades: 41, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "sui", timeframe: "position", winRate: 45.9, expectancy: 0.199, profitFactor: 1.37, maxDrawdownR: 5.91, trades: 61, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sui", timeframe: "position", winRate: 47.2, expectancy: 0.18, profitFactor: 1.35, maxDrawdownR: 3.17, trades: 36, tier: "proven" },
  { strategyId: "golden-trend", symbol: "sui", timeframe: "position", winRate: 47.9, expectancy: 0.173, profitFactor: 1.35, maxDrawdownR: 4.71, trades: 48, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sui", timeframe: "swing", winRate: 48.7, expectancy: 0.167, profitFactor: 1.43, maxDrawdownR: 6.55, trades: 152, tier: "proven" },
  // --- Expanded crypto universe (Binance-validated, same robustness bar) ---
  { strategyId: "pullback-buyer", symbol: "ripple", timeframe: "swing", winRate: 40.4, expectancy: 0.108, profitFactor: 1.41, maxDrawdownR: 3.97, trades: 57, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "polkadot", timeframe: "swing", winRate: 52.3, expectancy: 0.228, profitFactor: 1.56, maxDrawdownR: 4.64, trades: 149, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "polkadot", timeframe: "swing", winRate: 53.8, expectancy: 0.149, profitFactor: 1.57, maxDrawdownR: 3.4, trades: 80, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "tron", timeframe: "swing", winRate: 52, expectancy: 0.142, profitFactor: 1.44, maxDrawdownR: 8.45, trades: 102, tier: "proven" },
  { strategyId: "trend-rider", symbol: "matic-network", timeframe: "swing", winRate: 52.2, expectancy: 0.109, profitFactor: 1.44, maxDrawdownR: 5.09, trades: 201, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "matic-network", timeframe: "swing", winRate: 47.1, expectancy: 0.172, profitFactor: 1.37, maxDrawdownR: 20.33, trades: 240, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "matic-network", timeframe: "swing", winRate: 47.9, expectancy: 0.109, profitFactor: 1.32, maxDrawdownR: 6.21, trades: 73, tier: "proven" },
  { strategyId: "band-fade", symbol: "litecoin", timeframe: "swing", winRate: 56.6, expectancy: 0.248, profitFactor: 1.54, maxDrawdownR: 6.56, trades: 53, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "uniswap", timeframe: "swing", winRate: 49.4, expectancy: 0.105, profitFactor: 1.33, maxDrawdownR: 7.53, trades: 89, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "internet-computer", timeframe: "swing", winRate: 47.6, expectancy: 0.165, profitFactor: 1.37, maxDrawdownR: 8.65, trades: 143, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "internet-computer", timeframe: "swing", winRate: 48.8, expectancy: 0.102, profitFactor: 1.33, maxDrawdownR: 4.05, trades: 86, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "stellar", timeframe: "swing", winRate: 49, expectancy: 0.192, profitFactor: 1.45, maxDrawdownR: 5.73, trades: 157, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "stellar", timeframe: "swing", winRate: 50.6, expectancy: 0.115, profitFactor: 1.42, maxDrawdownR: 3.11, trades: 89, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "cosmos", timeframe: "swing", winRate: 49.7, expectancy: 0.138, profitFactor: 1.31, maxDrawdownR: 12.28, trades: 143, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "cosmos", timeframe: "swing", winRate: 54.1, expectancy: 0.145, profitFactor: 1.58, maxDrawdownR: 4.51, trades: 85, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "arbitrum", timeframe: "swing", winRate: 47.2, expectancy: 0.197, profitFactor: 1.46, maxDrawdownR: 6.51, trades: 144, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sei-network", timeframe: "swing", winRate: 49.7, expectancy: 0.181, profitFactor: 1.44, maxDrawdownR: 8.32, trades: 153, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "render-token", timeframe: "swing", winRate: 48.9, expectancy: 0.163, profitFactor: 1.4, maxDrawdownR: 7.68, trades: 133, tier: "proven" },
  { strategyId: "trend-rider", symbol: "fantom", timeframe: "swing", winRate: 50, expectancy: 0.079, profitFactor: 1.31, maxDrawdownR: 2.57, trades: 50, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "fantom", timeframe: "swing", winRate: 51.4, expectancy: 0.243, profitFactor: 1.53, maxDrawdownR: 6.99, trades: 74, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "fantom", timeframe: "swing", winRate: 52.6, expectancy: 0.137, profitFactor: 1.34, maxDrawdownR: 6.65, trades: 38, tier: "proven" },
  { strategyId: "golden-trend", symbol: "polkadot", timeframe: "position", winRate: 50.5, expectancy: 0.177, profitFactor: 1.42, maxDrawdownR: 5.68, trades: 97, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "polkadot", timeframe: "position", winRate: 53.1, expectancy: 0.361, profitFactor: 2.43, maxDrawdownR: 2.27, trades: 32, tier: "proven" },
  { strategyId: "band-fade", symbol: "polkadot", timeframe: "position", winRate: 48.4, expectancy: 0.202, profitFactor: 1.41, maxDrawdownR: 4.17, trades: 31, tier: "proven" },
  { strategyId: "trend-rider", symbol: "tron", timeframe: "position", winRate: 59.3, expectancy: 0.331, profitFactor: 2.31, maxDrawdownR: 5.02, trades: 86, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "tron", timeframe: "position", winRate: 63, expectancy: 0.4, profitFactor: 2.36, maxDrawdownR: 3.51, trades: 46, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "tron", timeframe: "position", winRate: 44.4, expectancy: 0.174, profitFactor: 1.33, maxDrawdownR: 4.13, trades: 63, tier: "proven" },
  { strategyId: "band-fade", symbol: "tron", timeframe: "position", winRate: 48.6, expectancy: 0.174, profitFactor: 1.32, maxDrawdownR: 5.13, trades: 37, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "matic-network", timeframe: "position", winRate: 63.6, expectancy: 0.427, profitFactor: 2.34, maxDrawdownR: 3.04, trades: 33, tier: "proven" },
  { strategyId: "trend-rider", symbol: "near", timeframe: "position", winRate: 49.4, expectancy: 0.146, profitFactor: 1.4, maxDrawdownR: 6.98, trades: 79, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "near", timeframe: "position", winRate: 55.1, expectancy: 0.257, profitFactor: 1.6, maxDrawdownR: 8.59, trades: 69, tier: "strong" },
  { strategyId: "golden-trend", symbol: "near", timeframe: "position", winRate: 47.8, expectancy: 0.167, profitFactor: 1.37, maxDrawdownR: 7.77, trades: 92, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "internet-computer", timeframe: "position", winRate: 47.5, expectancy: 0.154, profitFactor: 1.33, maxDrawdownR: 6.06, trades: 101, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "internet-computer", timeframe: "position", winRate: 50.9, expectancy: 0.271, profitFactor: 1.67, maxDrawdownR: 5.44, trades: 53, tier: "proven" },
  { strategyId: "trend-rider", symbol: "aptos", timeframe: "position", winRate: 60, expectancy: 0.186, profitFactor: 1.84, maxDrawdownR: 1.88, trades: 50, tier: "proven" },
  { strategyId: "band-fade", symbol: "stellar", timeframe: "position", winRate: 62.5, expectancy: 0.564, profitFactor: 2.55, maxDrawdownR: 3.19, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "filecoin", timeframe: "position", winRate: 59, expectancy: 0.125, profitFactor: 1.44, maxDrawdownR: 4.86, trades: 83, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "filecoin", timeframe: "position", winRate: 64.5, expectancy: 0.501, profitFactor: 3.05, maxDrawdownR: 2.89, trades: 31, tier: "proven" },
  { strategyId: "band-fade", symbol: "filecoin", timeframe: "position", winRate: 48.8, expectancy: 0.262, profitFactor: 1.59, maxDrawdownR: 3.6, trades: 41, tier: "proven" },
  { strategyId: "golden-trend", symbol: "hedera-hashgraph", timeframe: "position", winRate: 44.9, expectancy: 0.137, profitFactor: 1.32, maxDrawdownR: 7.78, trades: 98, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "hedera-hashgraph", timeframe: "position", winRate: 61.1, expectancy: 0.238, profitFactor: 1.82, maxDrawdownR: 2.83, trades: 36, tier: "proven" },
  { strategyId: "trend-rider", symbol: "arbitrum", timeframe: "position", winRate: 55.8, expectancy: 0.123, profitFactor: 1.38, maxDrawdownR: 6.4, trades: 43, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "arbitrum", timeframe: "position", winRate: 47.2, expectancy: 0.254, profitFactor: 1.56, maxDrawdownR: 4.18, trades: 36, tier: "proven" },
  { strategyId: "golden-trend", symbol: "arbitrum", timeframe: "position", winRate: 52.3, expectancy: 0.236, profitFactor: 1.65, maxDrawdownR: 5.32, trades: 44, tier: "proven" },
  { strategyId: "trend-rider", symbol: "optimism", timeframe: "position", winRate: 52.7, expectancy: 0.141, profitFactor: 1.45, maxDrawdownR: 4.38, trades: 55, tier: "proven" },
  { strategyId: "golden-trend", symbol: "optimism", timeframe: "position", winRate: 44.6, expectancy: 0.14, profitFactor: 1.3, maxDrawdownR: 6.89, trades: 65, tier: "proven" },
  { strategyId: "trend-rider", symbol: "injective-protocol", timeframe: "position", winRate: 54.9, expectancy: 0.097, profitFactor: 1.31, maxDrawdownR: 6.85, trades: 82, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "injective-protocol", timeframe: "position", winRate: 44.4, expectancy: 0.218, profitFactor: 1.49, maxDrawdownR: 9.59, trades: 63, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "injective-protocol", timeframe: "position", winRate: 54.8, expectancy: 0.187, profitFactor: 1.69, maxDrawdownR: 3.44, trades: 31, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "sei-network", timeframe: "position", winRate: 50, expectancy: 0.257, profitFactor: 1.52, maxDrawdownR: 6.1, trades: 52, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "sei-network", timeframe: "position", winRate: 53.1, expectancy: 0.315, profitFactor: 1.76, maxDrawdownR: 2.77, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "the-graph", timeframe: "position", winRate: 57.1, expectancy: 0.106, profitFactor: 1.37, maxDrawdownR: 5.12, trades: 77, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "the-graph", timeframe: "position", winRate: 53.5, expectancy: 0.27, profitFactor: 1.63, maxDrawdownR: 5.14, trades: 101, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "the-graph", timeframe: "position", winRate: 50, expectancy: 0.192, profitFactor: 1.46, maxDrawdownR: 3.53, trades: 64, tier: "proven" },
  { strategyId: "trend-rider", symbol: "fantom", timeframe: "position", winRate: 56.3, expectancy: 0.276, profitFactor: 1.93, maxDrawdownR: 2.7, trades: 64, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "fantom", timeframe: "position", winRate: 44.9, expectancy: 0.199, profitFactor: 1.4, maxDrawdownR: 7.41, trades: 89, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "fantom", timeframe: "position", winRate: 53.6, expectancy: 0.446, profitFactor: 2.13, maxDrawdownR: 3.82, trades: 56, tier: "proven" },
  { strategyId: "golden-trend", symbol: "fantom", timeframe: "position", winRate: 50.7, expectancy: 0.364, profitFactor: 1.82, maxDrawdownR: 6.14, trades: 73, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "fantom", timeframe: "position", winRate: 61.3, expectancy: 0.353, profitFactor: 2.61, maxDrawdownR: 1.77, trades: 31, tier: "proven" },
  // --- Expanded US equities (Alpaca data, same >=30 trades / expectancy>0 / PF>=1.3 bar) ---
  { strategyId: "trend-rider", symbol: "AMD", timeframe: "swing", winRate: 47, expectancy: 0.257, profitFactor: 1.74, maxDrawdownR: 4.75, trades: 66, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "AMD", timeframe: "swing", winRate: 53.2, expectancy: 0.289, profitFactor: 1.69, maxDrawdownR: 3.04, trades: 47, tier: "proven" },
  { strategyId: "golden-trend", symbol: "AMD", timeframe: "swing", winRate: 45.2, expectancy: 0.246, profitFactor: 1.52, maxDrawdownR: 5.74, trades: 84, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "AMD", timeframe: "swing", winRate: 55, expectancy: 0.22, profitFactor: 1.69, maxDrawdownR: 2.47, trades: 40, tier: "proven" },
  { strategyId: "trend-rider", symbol: "NFLX", timeframe: "swing", winRate: 52.9, expectancy: 0.209, profitFactor: 1.66, maxDrawdownR: 3.75, trades: 68, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NFLX", timeframe: "swing", winRate: 55.6, expectancy: 0.297, profitFactor: 1.75, maxDrawdownR: 7.08, trades: 81, tier: "proven" },
  { strategyId: "trend-rider", symbol: "COIN", timeframe: "swing", winRate: 50.9, expectancy: 0.178, profitFactor: 1.62, maxDrawdownR: 4.23, trades: 55, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "COIN", timeframe: "swing", winRate: 46.8, expectancy: 0.228, profitFactor: 1.5, maxDrawdownR: 4.29, trades: 47, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "COIN", timeframe: "swing", winRate: 51.5, expectancy: 0.275, profitFactor: 1.88, maxDrawdownR: 3.75, trades: 33, tier: "proven" },
  { strategyId: "trend-rider", symbol: "PLTR", timeframe: "swing", winRate: 52.9, expectancy: 0.189, profitFactor: 1.59, maxDrawdownR: 3.3, trades: 68, tier: "proven" },
  { strategyId: "golden-trend", symbol: "PLTR", timeframe: "swing", winRate: 47.1, expectancy: 0.185, profitFactor: 1.43, maxDrawdownR: 8.32, trades: 87, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "PLTR", timeframe: "swing", winRate: 55.6, expectancy: 0.084, profitFactor: 1.3, maxDrawdownR: 2.58, trades: 36, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "JPM", timeframe: "swing", winRate: 44.8, expectancy: 0.161, profitFactor: 1.31, maxDrawdownR: 10.11, trades: 96, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "JPM", timeframe: "swing", winRate: 70.6, expectancy: 0.243, profitFactor: 1.95, maxDrawdownR: 2.04, trades: 34, tier: "strong" },
  { strategyId: "golden-trend", symbol: "JPM", timeframe: "swing", winRate: 47.7, expectancy: 0.154, profitFactor: 1.33, maxDrawdownR: 9.01, trades: 86, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "SOFI", timeframe: "swing", winRate: 43.3, expectancy: 0.106, profitFactor: 1.34, maxDrawdownR: 6.18, trades: 30, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "GME", timeframe: "swing", winRate: 44, expectancy: 0.179, profitFactor: 1.36, maxDrawdownR: 4.74, trades: 50, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "GME", timeframe: "swing", winRate: 59.1, expectancy: 0.238, profitFactor: 1.83, maxDrawdownR: 3.24, trades: 44, tier: "strong" },
  { strategyId: "trend-rider", symbol: "AVGO", timeframe: "swing", winRate: 53.2, expectancy: 0.196, profitFactor: 1.61, maxDrawdownR: 4.28, trades: 77, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "AVGO", timeframe: "swing", winRate: 60, expectancy: 0.306, profitFactor: 1.99, maxDrawdownR: 3.48, trades: 45, tier: "strong" },
  { strategyId: "golden-trend", symbol: "AVGO", timeframe: "swing", winRate: 51.6, expectancy: 0.297, profitFactor: 1.7, maxDrawdownR: 8.23, trades: 91, tier: "proven" },
  { strategyId: "trend-rider", symbol: "CRM", timeframe: "swing", winRate: 59.2, expectancy: 0.107, profitFactor: 1.34, maxDrawdownR: 5.06, trades: 76, tier: "proven" },
  { strategyId: "golden-trend", symbol: "CRM", timeframe: "swing", winRate: 50, expectancy: 0.244, profitFactor: 1.6, maxDrawdownR: 7, trades: 84, tier: "proven" },
  { strategyId: "trend-rider", symbol: "ORCL", timeframe: "swing", winRate: 54.8, expectancy: 0.254, profitFactor: 1.9, maxDrawdownR: 2.81, trades: 73, tier: "strong" },
  { strategyId: "momentum-burst", symbol: "ORCL", timeframe: "swing", winRate: 48.9, expectancy: 0.21, profitFactor: 1.41, maxDrawdownR: 5.89, trades: 88, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "ORCL", timeframe: "swing", winRate: 50, expectancy: 0.346, profitFactor: 1.89, maxDrawdownR: 3.04, trades: 30, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "ORCL", timeframe: "swing", winRate: 50, expectancy: 0.155, profitFactor: 1.33, maxDrawdownR: 4.46, trades: 50, tier: "proven" },
  { strategyId: "golden-trend", symbol: "ORCL", timeframe: "swing", winRate: 48.8, expectancy: 0.255, profitFactor: 1.58, maxDrawdownR: 5.44, trades: 84, tier: "proven" },
  { strategyId: "trend-rider", symbol: "PYPL", timeframe: "swing", winRate: 52.2, expectancy: 0.122, profitFactor: 1.4, maxDrawdownR: 5.49, trades: 69, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MU", timeframe: "swing", winRate: 48, expectancy: 0.182, profitFactor: 1.54, maxDrawdownR: 7.66, trades: 75, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "MU", timeframe: "swing", winRate: 62.5, expectancy: 0.434, profitFactor: 2.73, maxDrawdownR: 2.1, trades: 32, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "MU", timeframe: "swing", winRate: 49, expectancy: 0.2, profitFactor: 1.42, maxDrawdownR: 8.01, trades: 51, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SMCI", timeframe: "swing", winRate: 45.7, expectancy: 0.122, profitFactor: 1.33, maxDrawdownR: 4.26, trades: 70, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "SMCI", timeframe: "swing", winRate: 57.5, expectancy: 0.26, profitFactor: 1.89, maxDrawdownR: 5.21, trades: 40, tier: "strong" },
  { strategyId: "trend-rider", symbol: "MSTR", timeframe: "swing", winRate: 51.6, expectancy: 0.171, profitFactor: 1.5, maxDrawdownR: 3.87, trades: 62, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "MSTR", timeframe: "swing", winRate: 48.5, expectancy: 0.315, profitFactor: 1.64, maxDrawdownR: 7.07, trades: 97, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "MSTR", timeframe: "swing", winRate: 56.6, expectancy: 0.402, profitFactor: 2.06, maxDrawdownR: 5, trades: 53, tier: "strong" },
  { strategyId: "golden-trend", symbol: "MSTR", timeframe: "swing", winRate: 50.6, expectancy: 0.276, profitFactor: 1.63, maxDrawdownR: 5.82, trades: 83, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "MSTR", timeframe: "swing", winRate: 59, expectancy: 0.347, profitFactor: 2.22, maxDrawdownR: 3.55, trades: 39, tier: "strong" },
  { strategyId: "trend-rider", symbol: "AMD", timeframe: "position", winRate: 55.6, expectancy: 0.301, profitFactor: 1.83, maxDrawdownR: 5.58, trades: 54, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "AMD", timeframe: "position", winRate: 48.9, expectancy: 0.295, profitFactor: 1.68, maxDrawdownR: 3.04, trades: 45, tier: "proven" },
  { strategyId: "golden-trend", symbol: "AMD", timeframe: "position", winRate: 39.2, expectancy: 0.278, profitFactor: 1.49, maxDrawdownR: 7.02, trades: 74, tier: "proven" },
  { strategyId: "trend-rider", symbol: "NFLX", timeframe: "position", winRate: 55.6, expectancy: 0.211, profitFactor: 1.6, maxDrawdownR: 4.21, trades: 54, tier: "proven" },
  { strategyId: "golden-trend", symbol: "NFLX", timeframe: "position", winRate: 49.3, expectancy: 0.27, profitFactor: 1.56, maxDrawdownR: 7.08, trades: 67, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "NFLX", timeframe: "position", winRate: 53.1, expectancy: 0.116, profitFactor: 1.31, maxDrawdownR: 3.45, trades: 32, tier: "proven" },
  { strategyId: "golden-trend", symbol: "COIN", timeframe: "position", winRate: 44.4, expectancy: 0.188, profitFactor: 1.38, maxDrawdownR: 4.49, trades: 63, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "COIN", timeframe: "position", winRate: 50, expectancy: 0.268, profitFactor: 1.81, maxDrawdownR: 3.09, trades: 30, tier: "proven" },
  { strategyId: "trend-rider", symbol: "PLTR", timeframe: "position", winRate: 52.9, expectancy: 0.216, profitFactor: 1.6, maxDrawdownR: 2.91, trades: 51, tier: "proven" },
  { strategyId: "golden-trend", symbol: "PLTR", timeframe: "position", winRate: 46.9, expectancy: 0.304, profitFactor: 1.63, maxDrawdownR: 5.75, trades: 64, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "PLTR", timeframe: "position", winRate: 57.6, expectancy: 0.115, profitFactor: 1.41, maxDrawdownR: 2.65, trades: 33, tier: "proven" },
  { strategyId: "trend-rider", symbol: "JPM", timeframe: "position", winRate: 55.6, expectancy: 0.121, profitFactor: 1.32, maxDrawdownR: 4.52, trades: 54, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "JPM", timeframe: "position", winRate: 47.1, expectancy: 0.326, profitFactor: 1.65, maxDrawdownR: 6.62, trades: 87, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "JPM", timeframe: "position", winRate: 60, expectancy: 0.284, profitFactor: 1.93, maxDrawdownR: 2.33, trades: 30, tier: "strong" },
  { strategyId: "golden-trend", symbol: "JPM", timeframe: "position", winRate: 46.3, expectancy: 0.188, profitFactor: 1.37, maxDrawdownR: 7.95, trades: 67, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "BABA", timeframe: "position", winRate: 58.3, expectancy: 0.116, profitFactor: 1.32, maxDrawdownR: 6.15, trades: 36, tier: "proven" },
  { strategyId: "trend-rider", symbol: "AVGO", timeframe: "position", winRate: 53.4, expectancy: 0.242, profitFactor: 1.73, maxDrawdownR: 4.55, trades: 58, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "AVGO", timeframe: "position", winRate: 53.8, expectancy: 0.378, profitFactor: 2.08, maxDrawdownR: 3.19, trades: 39, tier: "strong" },
  { strategyId: "golden-trend", symbol: "AVGO", timeframe: "position", winRate: 48, expectancy: 0.241, profitFactor: 1.5, maxDrawdownR: 8.04, trades: 75, tier: "proven" },
  { strategyId: "trend-rider", symbol: "CRM", timeframe: "position", winRate: 52.6, expectancy: 0.118, profitFactor: 1.31, maxDrawdownR: 5.22, trades: 57, tier: "proven" },
  { strategyId: "golden-trend", symbol: "CRM", timeframe: "position", winRate: 43.8, expectancy: 0.204, profitFactor: 1.41, maxDrawdownR: 6.12, trades: 64, tier: "proven" },
  { strategyId: "trend-rider", symbol: "ORCL", timeframe: "position", winRate: 50.9, expectancy: 0.236, profitFactor: 1.6, maxDrawdownR: 4.35, trades: 55, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "ORCL", timeframe: "position", winRate: 42.5, expectancy: 0.207, profitFactor: 1.36, maxDrawdownR: 9.69, trades: 87, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "ORCL", timeframe: "position", winRate: 56.5, expectancy: 0.495, profitFactor: 2.12, maxDrawdownR: 5.29, trades: 46, tier: "strong" },
  { strategyId: "golden-trend", symbol: "ORCL", timeframe: "position", winRate: 41.2, expectancy: 0.273, profitFactor: 1.53, maxDrawdownR: 5.1, trades: 68, tier: "proven" },
  { strategyId: "trend-rider", symbol: "PYPL", timeframe: "position", winRate: 52.7, expectancy: 0.114, profitFactor: 1.32, maxDrawdownR: 6.86, trades: 55, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SHOP", timeframe: "position", winRate: 50.9, expectancy: 0.136, profitFactor: 1.4, maxDrawdownR: 7.25, trades: 53, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MU", timeframe: "position", winRate: 55.4, expectancy: 0.307, profitFactor: 1.93, maxDrawdownR: 6.29, trades: 56, tier: "strong" },
  { strategyId: "golden-trend", symbol: "SMCI", timeframe: "position", winRate: 43.2, expectancy: 0.228, profitFactor: 1.44, maxDrawdownR: 7.86, trades: 74, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "SMCI", timeframe: "position", winRate: 45.9, expectancy: 0.149, profitFactor: 1.41, maxDrawdownR: 5.62, trades: 37, tier: "proven" },
  { strategyId: "trend-rider", symbol: "MSTR", timeframe: "position", winRate: 51, expectancy: 0.28, profitFactor: 1.77, maxDrawdownR: 4.58, trades: 49, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "MSTR", timeframe: "position", winRate: 45.6, expectancy: 0.323, profitFactor: 1.64, maxDrawdownR: 6.36, trades: 90, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "MSTR", timeframe: "position", winRate: 51, expectancy: 0.447, profitFactor: 2.02, maxDrawdownR: 4.85, trades: 51, tier: "proven" },
  { strategyId: "golden-trend", symbol: "MSTR", timeframe: "position", winRate: 44.3, expectancy: 0.291, profitFactor: 1.56, maxDrawdownR: 5.52, trades: 70, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "MSTR", timeframe: "position", winRate: 58.3, expectancy: 0.44, profitFactor: 2.41, maxDrawdownR: 2.56, trades: 36, tier: "strong" },
  // --- Expanded universe batch 3 (crypto via Binance, equities/ETFs via Alpaca; same >=30 trades / expectancy>0 / PF>=1.3 bar) ---
  { strategyId: "breakout-hunter", symbol: "maker", timeframe: "swing", winRate: 45.7, expectancy: 0.151, profitFactor: 1.32, maxDrawdownR: 6.69, trades: 81, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "maker", timeframe: "swing", winRate: 55.4, expectancy: 0.273, profitFactor: 2.13, maxDrawdownR: 2.29, trades: 56, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "algorand", timeframe: "swing", winRate: 52.3, expectancy: 0.211, profitFactor: 1.51, maxDrawdownR: 5.47, trades: 155, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "algorand", timeframe: "swing", winRate: 54.7, expectancy: 0.092, profitFactor: 1.31, maxDrawdownR: 6.77, trades: 86, tier: "proven" },
  { strategyId: "band-fade", symbol: "ethereum-classic", timeframe: "swing", winRate: 52.7, expectancy: 0.172, profitFactor: 1.34, maxDrawdownR: 8.5, trades: 55, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "eos", timeframe: "swing", winRate: 50, expectancy: 0.258, profitFactor: 1.58, maxDrawdownR: 3.72, trades: 58, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "eos", timeframe: "swing", winRate: 56.3, expectancy: 0.178, profitFactor: 1.58, maxDrawdownR: 4.49, trades: 32, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "decentraland", timeframe: "swing", winRate: 52.7, expectancy: 0.184, profitFactor: 1.46, maxDrawdownR: 5.04, trades: 148, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "chiliz", timeframe: "swing", winRate: 51.3, expectancy: 0.141, profitFactor: 1.34, maxDrawdownR: 6.05, trades: 150, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "chiliz", timeframe: "swing", winRate: 52.4, expectancy: 0.223, profitFactor: 1.79, maxDrawdownR: 3.5, trades: 82, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ADBE", timeframe: "swing", winRate: 59, expectancy: 0.247, profitFactor: 1.88, maxDrawdownR: 2.87, trades: 39, tier: "strong" },
  { strategyId: "trend-rider", symbol: "AMAT", timeframe: "swing", winRate: 52.9, expectancy: 0.146, profitFactor: 1.52, maxDrawdownR: 4.08, trades: 70, tier: "proven" },
  { strategyId: "golden-trend", symbol: "AMAT", timeframe: "swing", winRate: 47.7, expectancy: 0.164, profitFactor: 1.35, maxDrawdownR: 7.47, trades: 86, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "WMT", timeframe: "swing", winRate: 45.4, expectancy: 0.169, profitFactor: 1.32, maxDrawdownR: 9.25, trades: 97, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "WMT", timeframe: "swing", winRate: 59.1, expectancy: 0.299, profitFactor: 1.86, maxDrawdownR: 4.24, trades: 44, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "WMT", timeframe: "swing", winRate: 55.9, expectancy: 0.376, profitFactor: 2.07, maxDrawdownR: 4.04, trades: 34, tier: "strong" },
  { strategyId: "golden-trend", symbol: "WMT", timeframe: "swing", winRate: 46.2, expectancy: 0.213, profitFactor: 1.44, maxDrawdownR: 9.09, trades: 91, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "COST", timeframe: "swing", winRate: 57.1, expectancy: 0.268, profitFactor: 1.68, maxDrawdownR: 2.71, trades: 42, tier: "proven" },
  { strategyId: "golden-trend", symbol: "COST", timeframe: "swing", winRate: 50.6, expectancy: 0.213, profitFactor: 1.47, maxDrawdownR: 10.75, trades: 85, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "COST", timeframe: "swing", winRate: 58.3, expectancy: 0.193, profitFactor: 1.63, maxDrawdownR: 3.23, trades: 36, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "CVX", timeframe: "swing", winRate: 47.6, expectancy: 0.138, profitFactor: 1.31, maxDrawdownR: 5.62, trades: 42, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "CVX", timeframe: "swing", winRate: 54.8, expectancy: 0.118, profitFactor: 1.35, maxDrawdownR: 2.58, trades: 31, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "BAC", timeframe: "swing", winRate: 42.7, expectancy: 0.162, profitFactor: 1.3, maxDrawdownR: 6.68, trades: 96, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "ABNB", timeframe: "swing", winRate: 47.3, expectancy: 0.149, profitFactor: 1.32, maxDrawdownR: 7.18, trades: 93, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ABNB", timeframe: "swing", winRate: 54.5, expectancy: 0.172, profitFactor: 1.59, maxDrawdownR: 2.64, trades: 33, tier: "proven" },
  { strategyId: "trend-rider", symbol: "CRWD", timeframe: "swing", winRate: 52.2, expectancy: 0.117, profitFactor: 1.37, maxDrawdownR: 7.37, trades: 69, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "CRWD", timeframe: "swing", winRate: 53.3, expectancy: 0.336, profitFactor: 2.37, maxDrawdownR: 3.22, trades: 30, tier: "strong" },
  { strategyId: "golden-trend", symbol: "CRWD", timeframe: "swing", winRate: 46.3, expectancy: 0.169, profitFactor: 1.37, maxDrawdownR: 7.95, trades: 80, tier: "proven" },
  { strategyId: "trend-rider", symbol: "DDOG", timeframe: "swing", winRate: 52.1, expectancy: 0.121, profitFactor: 1.34, maxDrawdownR: 9.42, trades: 73, tier: "proven" },
  { strategyId: "trend-rider", symbol: "HOOD", timeframe: "swing", winRate: 50, expectancy: 0.103, profitFactor: 1.32, maxDrawdownR: 5.62, trades: 52, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "HOOD", timeframe: "swing", winRate: 51.2, expectancy: 0.209, profitFactor: 1.44, maxDrawdownR: 8.77, trades: 43, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "F", timeframe: "swing", winRate: 49, expectancy: 0.2, profitFactor: 1.42, maxDrawdownR: 5.28, trades: 51, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "F", timeframe: "swing", winRate: 48.8, expectancy: 0.138, profitFactor: 1.37, maxDrawdownR: 10.19, trades: 41, tier: "proven" },
  { strategyId: "trend-rider", symbol: "LLY", timeframe: "swing", winRate: 52, expectancy: 0.115, profitFactor: 1.38, maxDrawdownR: 9.09, trades: 75, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "LLY", timeframe: "swing", winRate: 50, expectancy: 0.136, profitFactor: 1.42, maxDrawdownR: 2.19, trades: 32, tier: "proven" },
  { strategyId: "golden-trend", symbol: "LLY", timeframe: "swing", winRate: 48.2, expectancy: 0.309, profitFactor: 1.72, maxDrawdownR: 10.72, trades: 85, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "UNH", timeframe: "swing", winRate: 56.4, expectancy: 0.229, profitFactor: 1.8, maxDrawdownR: 2.76, trades: 39, tier: "strong" },
  { strategyId: "trend-rider", symbol: "XLK", timeframe: "swing", winRate: 56.9, expectancy: 0.141, profitFactor: 1.51, maxDrawdownR: 3.63, trades: 72, tier: "proven" },
  { strategyId: "golden-trend", symbol: "XLK", timeframe: "swing", winRate: 48.3, expectancy: 0.246, profitFactor: 1.54, maxDrawdownR: 5.12, trades: 89, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SMH", timeframe: "swing", winRate: 57.9, expectancy: 0.16, profitFactor: 1.54, maxDrawdownR: 2.9, trades: 76, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SMH", timeframe: "swing", winRate: 57.9, expectancy: 0.194, profitFactor: 1.71, maxDrawdownR: 2.4, trades: 38, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SMH", timeframe: "swing", winRate: 52.2, expectancy: 0.272, profitFactor: 1.61, maxDrawdownR: 4.97, trades: 90, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "ARKK", timeframe: "swing", winRate: 47.9, expectancy: 0.23, profitFactor: 1.51, maxDrawdownR: 3.21, trades: 48, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ARKK", timeframe: "swing", winRate: 51.4, expectancy: 0.278, profitFactor: 2.16, maxDrawdownR: 1.3, trades: 37, tier: "strong" },
  { strategyId: "trend-rider", symbol: "GLD", timeframe: "swing", winRate: 55.3, expectancy: 0.301, profitFactor: 1.9, maxDrawdownR: 4.84, trades: 76, tier: "strong" },
  { strategyId: "pullback-buyer", symbol: "GLD", timeframe: "swing", winRate: 66.7, expectancy: 0.554, profitFactor: 3.85, maxDrawdownR: 2.08, trades: 33, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "GLD", timeframe: "swing", winRate: 47.1, expectancy: 0.189, profitFactor: 1.37, maxDrawdownR: 6.11, trades: 68, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GLD", timeframe: "swing", winRate: 49, expectancy: 0.339, profitFactor: 1.72, maxDrawdownR: 8.84, trades: 96, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "SLV", timeframe: "swing", winRate: 52.5, expectancy: 0.187, profitFactor: 1.4, maxDrawdownR: 8.02, trades: 59, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SLV", timeframe: "swing", winRate: 48.1, expectancy: 0.229, profitFactor: 1.5, maxDrawdownR: 8.77, trades: 81, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "XBI", timeframe: "swing", winRate: 66.7, expectancy: 0.256, profitFactor: 1.96, maxDrawdownR: 2.05, trades: 39, tier: "strong" },
  { strategyId: "golden-trend", symbol: "XBI", timeframe: "swing", winRate: 52.5, expectancy: 0.159, profitFactor: 1.4, maxDrawdownR: 6.33, trades: 80, tier: "proven" },
  { strategyId: "golden-trend", symbol: "DIA", timeframe: "swing", winRate: 54.7, expectancy: 0.134, profitFactor: 1.3, maxDrawdownR: 6.66, trades: 86, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SPX", timeframe: "swing", winRate: 64.8, expectancy: 0.135, profitFactor: 1.43, maxDrawdownR: 6.27, trades: 54, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SPX", timeframe: "swing", winRate: 52, expectancy: 0.163, profitFactor: 1.35, maxDrawdownR: 6.07, trades: 127, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "SPX", timeframe: "swing", winRate: 56.7, expectancy: 0.127, profitFactor: 1.37, maxDrawdownR: 5.82, trades: 67, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "aave", timeframe: "position", winRate: 52.9, expectancy: 0.162, profitFactor: 1.47, maxDrawdownR: 3.72, trades: 34, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "maker", timeframe: "position", winRate: 58.3, expectancy: 0.238, profitFactor: 1.79, maxDrawdownR: 3.87, trades: 36, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "algorand", timeframe: "position", winRate: 50.8, expectancy: 0.219, profitFactor: 1.49, maxDrawdownR: 8.44, trades: 63, tier: "proven" },
  { strategyId: "golden-trend", symbol: "algorand", timeframe: "position", winRate: 47.5, expectancy: 0.165, profitFactor: 1.38, maxDrawdownR: 7.91, trades: 101, tier: "proven" },
  { strategyId: "band-fade", symbol: "algorand", timeframe: "position", winRate: 48.4, expectancy: 0.19, profitFactor: 1.36, maxDrawdownR: 7.15, trades: 31, tier: "proven" },
  { strategyId: "trend-rider", symbol: "vechain", timeframe: "position", winRate: 57.6, expectancy: 0.197, profitFactor: 1.74, maxDrawdownR: 3.64, trades: 85, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "vechain", timeframe: "position", winRate: 48.7, expectancy: 0.253, profitFactor: 1.56, maxDrawdownR: 13.93, trades: 113, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "vechain", timeframe: "position", winRate: 47.2, expectancy: 0.251, profitFactor: 1.56, maxDrawdownR: 5.15, trades: 72, tier: "proven" },
  { strategyId: "golden-trend", symbol: "vechain", timeframe: "position", winRate: 50.5, expectancy: 0.157, profitFactor: 1.36, maxDrawdownR: 5.58, trades: 103, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "vechain", timeframe: "position", winRate: 64.9, expectancy: 0.391, profitFactor: 2.67, maxDrawdownR: 2.01, trades: 37, tier: "strong" },
  { strategyId: "trend-rider", symbol: "theta-token", timeframe: "position", winRate: 58.8, expectancy: 0.22, profitFactor: 1.78, maxDrawdownR: 3.86, trades: 80, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "theta-token", timeframe: "position", winRate: 46.2, expectancy: 0.193, profitFactor: 1.38, maxDrawdownR: 9.19, trades: 119, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "theta-token", timeframe: "position", winRate: 51.4, expectancy: 0.303, profitFactor: 1.7, maxDrawdownR: 7.12, trades: 72, tier: "proven" },
  { strategyId: "golden-trend", symbol: "theta-token", timeframe: "position", winRate: 49, expectancy: 0.173, profitFactor: 1.41, maxDrawdownR: 7.63, trades: 98, tier: "proven" },
  { strategyId: "trend-rider", symbol: "ethereum-classic", timeframe: "position", winRate: 51.2, expectancy: 0.141, profitFactor: 1.4, maxDrawdownR: 4.62, trades: 82, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "ethereum-classic", timeframe: "position", winRate: 44.3, expectancy: 0.271, profitFactor: 1.63, maxDrawdownR: 3.66, trades: 61, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ethereum-classic", timeframe: "position", winRate: 50, expectancy: 0.161, profitFactor: 1.39, maxDrawdownR: 6.76, trades: 42, tier: "proven" },
  { strategyId: "band-fade", symbol: "ethereum-classic", timeframe: "position", winRate: 50, expectancy: 0.253, profitFactor: 1.52, maxDrawdownR: 3.06, trades: 42, tier: "proven" },
  { strategyId: "trend-rider", symbol: "eos", timeframe: "position", winRate: 51.5, expectancy: 0.118, profitFactor: 1.35, maxDrawdownR: 4.38, trades: 68, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "eos", timeframe: "position", winRate: 42.1, expectancy: 0.197, profitFactor: 1.4, maxDrawdownR: 4.94, trades: 57, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "eos", timeframe: "position", winRate: 64.5, expectancy: 0.265, profitFactor: 2.18, maxDrawdownR: 2.14, trades: 31, tier: "strong" },
  { strategyId: "trend-rider", symbol: "tezos", timeframe: "position", winRate: 58.4, expectancy: 0.17, profitFactor: 1.62, maxDrawdownR: 2.97, trades: 89, tier: "proven" },
  { strategyId: "golden-trend", symbol: "tezos", timeframe: "position", winRate: 44.4, expectancy: 0.138, profitFactor: 1.31, maxDrawdownR: 6.03, trades: 99, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "tezos", timeframe: "position", winRate: 50, expectancy: 0.16, profitFactor: 1.45, maxDrawdownR: 3.88, trades: 34, tier: "proven" },
  { strategyId: "trend-rider", symbol: "axie-infinity", timeframe: "position", winRate: 56.1, expectancy: 0.155, profitFactor: 1.53, maxDrawdownR: 3.55, trades: 82, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "axie-infinity", timeframe: "position", winRate: 52.3, expectancy: 0.348, profitFactor: 1.78, maxDrawdownR: 9.23, trades: 107, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "axie-infinity", timeframe: "position", winRate: 55.9, expectancy: 0.396, profitFactor: 1.98, maxDrawdownR: 6.14, trades: 59, tier: "strong" },
  { strategyId: "golden-trend", symbol: "axie-infinity", timeframe: "position", winRate: 54.3, expectancy: 0.234, profitFactor: 1.57, maxDrawdownR: 7.28, trades: 92, tier: "proven" },
  { strategyId: "trend-rider", symbol: "the-sandbox", timeframe: "position", winRate: 53.5, expectancy: 0.209, profitFactor: 1.73, maxDrawdownR: 3.77, trades: 86, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "the-sandbox", timeframe: "position", winRate: 47, expectancy: 0.156, profitFactor: 1.32, maxDrawdownR: 5.56, trades: 66, tier: "proven" },
  { strategyId: "golden-trend", symbol: "the-sandbox", timeframe: "position", winRate: 46.9, expectancy: 0.172, profitFactor: 1.38, maxDrawdownR: 5.96, trades: 96, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "decentraland", timeframe: "position", winRate: 46.1, expectancy: 0.169, profitFactor: 1.33, maxDrawdownR: 8.17, trades: 115, tier: "proven" },
  { strategyId: "trend-rider", symbol: "gala", timeframe: "position", winRate: 57.1, expectancy: 0.122, profitFactor: 1.35, maxDrawdownR: 4.42, trades: 70, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "gala", timeframe: "position", winRate: 54.5, expectancy: 0.244, profitFactor: 1.55, maxDrawdownR: 4.35, trades: 55, tier: "proven" },
  { strategyId: "golden-trend", symbol: "gala", timeframe: "position", winRate: 51.2, expectancy: 0.172, profitFactor: 1.39, maxDrawdownR: 10.59, trades: 80, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "chiliz", timeframe: "position", winRate: 46.6, expectancy: 0.224, profitFactor: 1.45, maxDrawdownR: 11.29, trades: 131, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "chiliz", timeframe: "position", winRate: 48.5, expectancy: 0.224, profitFactor: 1.49, maxDrawdownR: 5.25, trades: 68, tier: "proven" },
  { strategyId: "band-fade", symbol: "chiliz", timeframe: "position", winRate: 52.6, expectancy: 0.253, profitFactor: 1.53, maxDrawdownR: 6.08, trades: 38, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "curve-dao-token", timeframe: "position", winRate: 46.2, expectancy: 0.21, profitFactor: 1.6, maxDrawdownR: 2.65, trades: 39, tier: "proven" },
  { strategyId: "trend-rider", symbol: "thorchain", timeframe: "position", winRate: 52.4, expectancy: 0.128, profitFactor: 1.43, maxDrawdownR: 4.76, trades: 82, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "thorchain", timeframe: "position", winRate: 48.2, expectancy: 0.277, profitFactor: 1.59, maxDrawdownR: 8.21, trades: 110, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "thorchain", timeframe: "position", winRate: 47.3, expectancy: 0.137, profitFactor: 1.31, maxDrawdownR: 11.45, trades: 74, tier: "proven" },
  { strategyId: "golden-trend", symbol: "thorchain", timeframe: "position", winRate: 48.5, expectancy: 0.218, profitFactor: 1.5, maxDrawdownR: 8.59, trades: 101, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "thorchain", timeframe: "position", winRate: 57.1, expectancy: 0.193, profitFactor: 1.63, maxDrawdownR: 5.4, trades: 35, tier: "proven" },
  { strategyId: "golden-trend", symbol: "immutable-x", timeframe: "position", winRate: 50, expectancy: 0.177, profitFactor: 1.44, maxDrawdownR: 4.56, trades: 68, tier: "proven" },
  { strategyId: "trend-rider", symbol: "shiba-inu", timeframe: "position", winRate: 52.9, expectancy: 0.106, profitFactor: 1.35, maxDrawdownR: 3.86, trades: 70, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "shiba-inu", timeframe: "position", winRate: 46.9, expectancy: 0.178, profitFactor: 1.36, maxDrawdownR: 5.61, trades: 96, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "shiba-inu", timeframe: "position", winRate: 50, expectancy: 0.269, profitFactor: 1.82, maxDrawdownR: 4.06, trades: 34, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "ADBE", timeframe: "position", winRate: 52.8, expectancy: 0.263, profitFactor: 1.78, maxDrawdownR: 5.67, trades: 36, tier: "proven" },
  { strategyId: "trend-rider", symbol: "AMAT", timeframe: "position", winRate: 51.8, expectancy: 0.115, profitFactor: 1.3, maxDrawdownR: 4.7, trades: 56, tier: "proven" },
  { strategyId: "golden-trend", symbol: "AMAT", timeframe: "position", winRate: 48.5, expectancy: 0.256, profitFactor: 1.52, maxDrawdownR: 8.67, trades: 66, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "WMT", timeframe: "position", winRate: 44.9, expectancy: 0.217, profitFactor: 1.4, maxDrawdownR: 8.88, trades: 89, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "WMT", timeframe: "position", winRate: 52.8, expectancy: 0.303, profitFactor: 1.81, maxDrawdownR: 4.54, trades: 36, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "WMT", timeframe: "position", winRate: 51.5, expectancy: 0.441, profitFactor: 2.2, maxDrawdownR: 2.27, trades: 33, tier: "strong" },
  { strategyId: "golden-trend", symbol: "WMT", timeframe: "position", winRate: 44.1, expectancy: 0.273, profitFactor: 1.52, maxDrawdownR: 8.16, trades: 68, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "HD", timeframe: "position", winRate: 44.9, expectancy: 0.231, profitFactor: 1.43, maxDrawdownR: 8.52, trades: 89, tier: "proven" },
  { strategyId: "golden-trend", symbol: "HD", timeframe: "position", winRate: 50.9, expectancy: 0.167, profitFactor: 1.35, maxDrawdownR: 6.1, trades: 57, tier: "proven" },
  { strategyId: "trend-rider", symbol: "COST", timeframe: "position", winRate: 48.3, expectancy: 0.15, profitFactor: 1.37, maxDrawdownR: 10.3, trades: 60, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "COST", timeframe: "position", winRate: 53.3, expectancy: 0.153, profitFactor: 1.35, maxDrawdownR: 3.63, trades: 30, tier: "proven" },
  { strategyId: "golden-trend", symbol: "COST", timeframe: "position", winRate: 45.7, expectancy: 0.302, profitFactor: 1.6, maxDrawdownR: 10.2, trades: 70, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "COST", timeframe: "position", winRate: 58.8, expectancy: 0.324, profitFactor: 2.07, maxDrawdownR: 3.33, trades: 34, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "XOM", timeframe: "position", winRate: 65.6, expectancy: 0.146, profitFactor: 1.48, maxDrawdownR: 3.66, trades: 32, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "CVX", timeframe: "position", winRate: 53.3, expectancy: 0.293, profitFactor: 1.94, maxDrawdownR: 2.53, trades: 30, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "KO", timeframe: "position", winRate: 51.3, expectancy: 0.17, profitFactor: 1.39, maxDrawdownR: 5.17, trades: 39, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "BAC", timeframe: "position", winRate: 44, expectancy: 0.183, profitFactor: 1.33, maxDrawdownR: 5.15, trades: 91, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "GS", timeframe: "position", winRate: 52.9, expectancy: 0.218, profitFactor: 1.6, maxDrawdownR: 6.77, trades: 34, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ABNB", timeframe: "position", winRate: 53.1, expectancy: 0.114, profitFactor: 1.31, maxDrawdownR: 3.74, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "CRWD", timeframe: "position", winRate: 52.8, expectancy: 0.184, profitFactor: 1.54, maxDrawdownR: 5.53, trades: 53, tier: "proven" },
  { strategyId: "golden-trend", symbol: "CRWD", timeframe: "position", winRate: 47.1, expectancy: 0.241, profitFactor: 1.48, maxDrawdownR: 7.55, trades: 68, tier: "proven" },
  { strategyId: "trend-rider", symbol: "DDOG", timeframe: "position", winRate: 52.6, expectancy: 0.146, profitFactor: 1.37, maxDrawdownR: 7.54, trades: 57, tier: "proven" },
  { strategyId: "trend-rider", symbol: "HOOD", timeframe: "position", winRate: 50, expectancy: 0.191, profitFactor: 1.5, maxDrawdownR: 3.38, trades: 40, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "HOOD", timeframe: "position", winRate: 43.9, expectancy: 0.295, profitFactor: 1.57, maxDrawdownR: 9.55, trades: 41, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "F", timeframe: "position", winRate: 48.7, expectancy: 0.2, profitFactor: 1.44, maxDrawdownR: 11.87, trades: 39, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "NKE", timeframe: "position", winRate: 54.1, expectancy: 0.127, profitFactor: 1.34, maxDrawdownR: 4.66, trades: 37, tier: "proven" },
  { strategyId: "trend-rider", symbol: "LLY", timeframe: "position", winRate: 54.8, expectancy: 0.186, profitFactor: 1.48, maxDrawdownR: 6.94, trades: 62, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "LLY", timeframe: "position", winRate: 51.9, expectancy: 0.254, profitFactor: 1.53, maxDrawdownR: 3.11, trades: 52, tier: "proven" },
  { strategyId: "golden-trend", symbol: "LLY", timeframe: "position", winRate: 45.1, expectancy: 0.289, profitFactor: 1.58, maxDrawdownR: 10.17, trades: 71, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "UNH", timeframe: "position", winRate: 48.6, expectancy: 0.221, profitFactor: 1.58, maxDrawdownR: 3.19, trades: 35, tier: "proven" },
  { strategyId: "trend-rider", symbol: "XLK", timeframe: "position", winRate: 55.4, expectancy: 0.197, profitFactor: 1.55, maxDrawdownR: 3.17, trades: 56, tier: "proven" },
  { strategyId: "golden-trend", symbol: "XLK", timeframe: "position", winRate: 44.9, expectancy: 0.268, profitFactor: 1.51, maxDrawdownR: 5.66, trades: 69, tier: "proven" },
  { strategyId: "trend-rider", symbol: "SMH", timeframe: "position", winRate: 52.5, expectancy: 0.244, profitFactor: 1.69, maxDrawdownR: 4.14, trades: 59, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SMH", timeframe: "position", winRate: 60.6, expectancy: 0.241, profitFactor: 1.78, maxDrawdownR: 3, trades: 33, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SMH", timeframe: "position", winRate: 43.2, expectancy: 0.25, profitFactor: 1.48, maxDrawdownR: 6.79, trades: 74, tier: "proven" },
  { strategyId: "momentum-burst", symbol: "ARKK", timeframe: "position", winRate: 42, expectancy: 0.177, profitFactor: 1.31, maxDrawdownR: 7.59, trades: 100, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "ARKK", timeframe: "position", winRate: 50, expectancy: 0.228, profitFactor: 1.76, maxDrawdownR: 2.38, trades: 32, tier: "proven" },
  { strategyId: "trend-rider", symbol: "GLD", timeframe: "position", winRate: 57.6, expectancy: 0.398, profitFactor: 2.45, maxDrawdownR: 3.3, trades: 59, tier: "strong" },
  { strategyId: "breakout-hunter", symbol: "GLD", timeframe: "position", winRate: 46.9, expectancy: 0.214, profitFactor: 1.42, maxDrawdownR: 6.2, trades: 64, tier: "proven" },
  { strategyId: "golden-trend", symbol: "GLD", timeframe: "position", winRate: 55.4, expectancy: 0.562, profitFactor: 2.3, maxDrawdownR: 4.52, trades: 74, tier: "strong" },
  { strategyId: "supertrend-follow", symbol: "GLD", timeframe: "position", winRate: 50, expectancy: 0.142, profitFactor: 1.36, maxDrawdownR: 5.44, trades: 42, tier: "proven" },
  { strategyId: "golden-trend", symbol: "SLV", timeframe: "position", winRate: 46.3, expectancy: 0.252, profitFactor: 1.47, maxDrawdownR: 10.19, trades: 67, tier: "proven" },
  { strategyId: "supertrend-follow", symbol: "XLV", timeframe: "position", winRate: 63.6, expectancy: 0.15, profitFactor: 1.41, maxDrawdownR: 4.1, trades: 33, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "XBI", timeframe: "position", winRate: 48.6, expectancy: 0.176, profitFactor: 1.46, maxDrawdownR: 4.02, trades: 37, tier: "proven" },
  { strategyId: "golden-trend", symbol: "XBI", timeframe: "position", winRate: 48.3, expectancy: 0.233, profitFactor: 1.55, maxDrawdownR: 5.02, trades: 60, tier: "proven" },
  { strategyId: "pullback-buyer", symbol: "SPX", timeframe: "position", winRate: 60, expectancy: 0.118, profitFactor: 1.32, maxDrawdownR: 8.14, trades: 100, tier: "proven" },
  { strategyId: "breakout-hunter", symbol: "SPX", timeframe: "position", winRate: 46.3, expectancy: 0.185, profitFactor: 1.34, maxDrawdownR: 4.74, trades: 54, tier: "proven" },
]

// All pairings for a given ticker, best edge first.
export function provenForSymbol(symbol: string): ProvenPairing[] {
  return PROVEN_PAIRINGS.filter((p) => p.symbol === symbol).sort((a, b) => b.expectancy - a.expectancy)
}

// The single best-fit strategy for a ticker (optionally at a fixed timeframe).
export function bestForSymbol(symbol: string, timeframe?: "swing" | "position"): ProvenPairing | null {
  const list = provenForSymbol(symbol).filter((p) => !timeframe || p.timeframe === timeframe)
  return list[0] ?? null
}

// Exact stats for one strategy/ticker/timeframe assignment, or null if it never
// passed testing (so the UI can honestly say "not proven on this market").
export function statsFor(
  strategyId: string,
  symbol: string,
  timeframe: "swing" | "position",
): ProvenPairing | null {
  return (
    PROVEN_PAIRINGS.find(
      (p) => p.strategyId === strategyId && p.symbol === symbol && p.timeframe === timeframe,
    ) ?? null
  )
}

// Every ticker that has at least one proven strategy.
export function provenSymbols(): string[] {
  return Array.from(new Set(PROVEN_PAIRINGS.map((p) => p.symbol)))
}
