// ============================================================================
// OUT-OF-SAMPLE VALIDATION — the gold standard on top of the proven mapping.
//
// Every pairing in `mapping.ts` cleared the in-sample robustness bar. This file
// records how each one held up on data the strategy never "saw". We split each
// instrument's deep history into ordered time segments plus a held-out final
// slice, re-ran the SAME strategy, and recorded whether the edge persisted.
//
// These verdicts are produced by /api/playbook-validate (the walk-forward engine
// in lib/walk-forward.ts) and regenerated by scripts/regen-validation.mjs. They
// are NOT hand-authored. Stocks validate on Alpaca data, crypto on Binance.
//
// Verdicts:
//   robust       = edge held out-of-sample AND a majority of folds stayed
//                  positive. These earn the "Survived out-of-sample" gold badge.
//   fragile      = edge weakened or flipped negative on unseen data. Real but
//                  regime-dependent — size down, do not lean on it.
//   inconclusive = not enough clean history at this timeframe to judge OOS yet
//                  (too few folds/trades). Surfaced honestly, never dressed up.
//
// Last regenerated across 145 pairings: 30 robust, 61 fragile, 54 inconclusive.
// We surface every verdict honestly rather than hiding the ones that failed.
// ============================================================================

export type OosVerdict = "robust" | "fragile" | "inconclusive"

export type OosResult = {
  verdict: OosVerdict
  consistency: number // % of time segments that stayed profitable
  positiveFolds: number
  totalFolds: number
  holdoutExpectancy: number | null // R per trade on the unseen held-out slice
}

// Keyed by `${strategyId}|${symbol}|${timeframe}`.
export const OOS_VALIDATION: Record<string, OosResult> = {
  // --- Intraday / same-session (15m walk-forward) ---
  "supertrend-follow|AMZN|intraday": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.291 },
  "band-fade|fantom|intraday": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.892 },
  "supertrend-follow|META|intraday": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.036 },
  "breakout-hunter|MSFT|intraday": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.751 },
  "pullback-buyer|MSFT|intraday": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 1, holdoutExpectancy: 0.739 },
  "trend-rider|MSFT|intraday": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.342 },
  "supertrend-follow|TSLA|intraday": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.262 },
  // --- Swing (daily walk-forward) ---
  "momentum-burst|AAPL|swing": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.119 },
  "supertrend-follow|AAPL|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.137 },
  "pullback-buyer|AMZN|swing": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: -0.487 },
  "supertrend-follow|AMZN|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.31 },
  "breakout-hunter|arbitrum|swing": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.206 },
  "breakout-hunter|cardano|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.112 },
  "momentum-burst|cardano|swing": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.052 },
  "supertrend-follow|cardano|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.27 },
  "supertrend-follow|cosmos|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.025 },
  "pullback-buyer|DIA|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.33 },
  "pullback-buyer|dogecoin|swing": { verdict: "inconclusive", consistency: 100, positiveFolds: 2, totalFolds: 2, holdoutExpectancy: 0.095 },
  "supertrend-follow|dogecoin|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.025 },
  "supertrend-follow|ethereum|swing": { verdict: "fragile", consistency: 25, positiveFolds: 1, totalFolds: 4, holdoutExpectancy: 0.092 },
  "breakout-hunter|fantom|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 1.017 },
  "momentum-burst|fantom|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.457 },
  "trend-rider|fantom|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.127 },
  "breakout-hunter|GOOGL|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.343 },
  "golden-trend|GOOGL|swing": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.558 },
  "pullback-buyer|GOOGL|swing": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.564 },
  "trend-rider|GOOGL|swing": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.49 },
  "breakout-hunter|internet-computer|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.044 },
  "supertrend-follow|internet-computer|swing": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.009 },
  "band-fade|litecoin|swing": { verdict: "robust", consistency: 100, positiveFolds: 3, totalFolds: 3, holdoutExpectancy: 0.207 },
  "momentum-burst|matic-network|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.217 },
  "supertrend-follow|matic-network|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.077 },
  "trend-rider|matic-network|swing": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: -0.015 },
  "golden-trend|META|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.175 },
  "trend-rider|META|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.233 },
  "golden-trend|MSFT|swing": { verdict: "fragile", consistency: 25, positiveFolds: 1, totalFolds: 4, holdoutExpectancy: 0.063 },
  "trend-rider|MSFT|swing": { verdict: "inconclusive", consistency: 100, positiveFolds: 2, totalFolds: 2, holdoutExpectancy: 0.162 },
  "breakout-hunter|NVDA|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.535 },
  "golden-trend|NVDA|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.091 },
  "trend-rider|NVDA|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.223 },
  "breakout-hunter|polkadot|swing": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.059 },
  "supertrend-follow|polkadot|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.045 },
  "golden-trend|QQQ|swing": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.31 },
  "pullback-buyer|QQQ|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.08 },
  "trend-rider|QQQ|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.031 },
  "breakout-hunter|render-token|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.062 },
  "pullback-buyer|ripple|swing": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.066 },
  "breakout-hunter|sei-network|swing": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.116 },
  "golden-trend|SPX|swing": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.078 },
  "pullback-buyer|SPX|swing": { verdict: "robust", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: 0.144 },
  "supertrend-follow|SPX|swing": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.208 },
  "golden-trend|SPY|swing": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.172 },
  "trend-rider|SPY|swing": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.012 },
  "breakout-hunter|stellar|swing": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.154 },
  "supertrend-follow|stellar|swing": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.085 },
  "breakout-hunter|sui|swing": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.209 },
  "pullback-buyer|tron|swing": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.431 },
  "breakout-hunter|TSLA|swing": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 1, holdoutExpectancy: 0.028 },
  "supertrend-follow|uniswap|swing": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.115 },
  // --- Position (daily/weekly walk-forward) ---
  "momentum-burst|AAPL|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.153 },
  "supertrend-follow|AAPL|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.071 },
  "supertrend-follow|AMZN|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.205 },
  "trend-rider|aptos|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.2 },
  "breakout-hunter|arbitrum|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.471 },
  "golden-trend|arbitrum|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.092 },
  "trend-rider|arbitrum|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.248 },
  "breakout-hunter|avalanche-2|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.194 },
  "momentum-burst|avalanche-2|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.095 },
  "supertrend-follow|avalanche-2|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.221 },
  "trend-rider|avalanche-2|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.128 },
  "breakout-hunter|binancecoin|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.347 },
  "momentum-burst|binancecoin|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.331 },
  "pullback-buyer|binancecoin|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.539 },
  "trend-rider|binancecoin|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.121 },
  "breakout-hunter|bitcoin|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.059 },
  "golden-trend|bitcoin|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.092 },
  "momentum-burst|bitcoin|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.152 },
  "trend-rider|bitcoin|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.314 },
  "band-fade|cardano|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 1, holdoutExpectancy: 0.599 },
  "golden-trend|cardano|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.142 },
  "trend-rider|cardano|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.047 },
  "golden-trend|DIA|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.664 },
  "breakout-hunter|dogecoin|position": { verdict: "robust", consistency: 100, positiveFolds: 3, totalFolds: 3, holdoutExpectancy: 0.541 },
  "momentum-burst|dogecoin|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.001 },
  "supertrend-follow|dogecoin|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.427 },
  "breakout-hunter|ethereum|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.261 },
  "pullback-buyer|ethereum|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: -0.159 },
  "breakout-hunter|fantom|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.271 },
  "golden-trend|fantom|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.133 },
  "momentum-burst|fantom|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.313 },
  "supertrend-follow|fantom|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.132 },
  "trend-rider|fantom|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.047 },
  "band-fade|filecoin|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.177 },
  "supertrend-follow|filecoin|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.446 },
  "trend-rider|filecoin|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.014 },
  "breakout-hunter|GOOGL|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.62 },
  "golden-trend|GOOGL|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.697 },
  "trend-rider|GOOGL|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.692 },
  "golden-trend|hedera-hashgraph|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: -0.094 },
  "supertrend-follow|hedera-hashgraph|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.128 },
  "breakout-hunter|injective-protocol|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.244 },
  "supertrend-follow|injective-protocol|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 1, holdoutExpectancy: 0.467 },
  "trend-rider|injective-protocol|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.138 },
  "breakout-hunter|internet-computer|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 2, holdoutExpectancy: 0.986 },
  "momentum-burst|internet-computer|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.085 },
  "momentum-burst|matic-network|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: null },
  "golden-trend|META|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.091 },
  "trend-rider|META|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.356 },
  "breakout-hunter|near|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.111 },
  "golden-trend|near|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: -0.136 },
  "trend-rider|near|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.101 },
  "breakout-hunter|NVDA|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.238 },
  "golden-trend|NVDA|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.159 },
  "trend-rider|NVDA|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: -0.217 },
  "trend-rider|optimism|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: 0.282 },
  "band-fade|polkadot|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.26 },
  "golden-trend|polkadot|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.452 },
  "supertrend-follow|polkadot|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 1, holdoutExpectancy: -0.03 },
  "breakout-hunter|QQQ|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.868 },
  "golden-trend|QQQ|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.313 },
  "trend-rider|QQQ|position": { verdict: "robust", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: 0.166 },
  "breakout-hunter|sei-network|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.087 },
  "momentum-burst|sei-network|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.351 },
  "breakout-hunter|solana|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: -0.226 },
  "golden-trend|solana|position": { verdict: "fragile", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.063 },
  "supertrend-follow|solana|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.397 },
  "trend-rider|solana|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.112 },
  "breakout-hunter|SPX|position": { verdict: "fragile", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: -0.225 },
  "pullback-buyer|SPX|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.144 },
  "breakout-hunter|SPY|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.326 },
  "golden-trend|SPY|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.456 },
  "band-fade|stellar|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: -0.022 },
  "breakout-hunter|sui|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.149 },
  "golden-trend|sui|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.035 },
  "momentum-burst|sui|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.084 },
  "trend-rider|sui|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.088 },
  "breakout-hunter|the-graph|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.266 },
  "momentum-burst|the-graph|position": { verdict: "robust", consistency: 100, positiveFolds: 4, totalFolds: 4, holdoutExpectancy: 0.202 },
  "trend-rider|the-graph|position": { verdict: "fragile", consistency: 50, positiveFolds: 2, totalFolds: 4, holdoutExpectancy: 0.33 },
  "band-fade|tron|position": { verdict: "inconclusive", consistency: 100, positiveFolds: 1, totalFolds: 1, holdoutExpectancy: -0.138 },
  "breakout-hunter|tron|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.387 },
  "pullback-buyer|tron|position": { verdict: "fragile", consistency: 67, positiveFolds: 2, totalFolds: 3, holdoutExpectancy: 0.078 },
  "trend-rider|tron|position": { verdict: "robust", consistency: 75, positiveFolds: 3, totalFolds: 4, holdoutExpectancy: 0.189 },
  "breakout-hunter|TSLA|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: -0.453 },
  "supertrend-follow|TSLA|position": { verdict: "inconclusive", consistency: 0, positiveFolds: 0, totalFolds: 0, holdoutExpectancy: 0.576 },
}

export function oosFor(strategyId: string, symbol: string, timeframe: string): OosResult | null {
  return OOS_VALIDATION[`${strategyId}|${symbol}|${timeframe}`] ?? null
}

export function isRobust(strategyId: string, symbol: string, timeframe: string): boolean {
  return oosFor(strategyId, symbol, timeframe)?.verdict === "robust"
}
